/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.110.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.AgentContextType;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * AgentSendMessageRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class AgentSendMessageRequest {
  public static final String SERIALIZED_NAME_CONTEXT_ID = "contextId";
  @SerializedName(SERIALIZED_NAME_CONTEXT_ID)
  @javax.annotation.Nullable
  private String contextId;

  public static final String SERIALIZED_NAME_CONTEXT_METADATA = "contextMetadata";
  @SerializedName(SERIALIZED_NAME_CONTEXT_METADATA)
  @javax.annotation.Nullable
  private String contextMetadata;

  public static final String SERIALIZED_NAME_CONTEXT_TYPE = "contextType";
  @SerializedName(SERIALIZED_NAME_CONTEXT_TYPE)
  @javax.annotation.Nullable
  private AgentContextType contextType;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public AgentSendMessageRequest() {
  }

  public AgentSendMessageRequest contextId(@javax.annotation.Nullable String contextId) {
    this.contextId = contextId;
    return this;
  }

  /**
   * Get contextId
   * @return contextId
   */
  @javax.annotation.Nullable
  public String getContextId() {
    return contextId;
  }

  public void setContextId(@javax.annotation.Nullable String contextId) {
    this.contextId = contextId;
  }


  public AgentSendMessageRequest contextMetadata(@javax.annotation.Nullable String contextMetadata) {
    this.contextMetadata = contextMetadata;
    return this;
  }

  /**
   * Get contextMetadata
   * @return contextMetadata
   */
  @javax.annotation.Nullable
  public String getContextMetadata() {
    return contextMetadata;
  }

  public void setContextMetadata(@javax.annotation.Nullable String contextMetadata) {
    this.contextMetadata = contextMetadata;
  }


  public AgentSendMessageRequest contextType(@javax.annotation.Nullable AgentContextType contextType) {
    this.contextType = contextType;
    return this;
  }

  /**
   * Get contextType
   * @return contextType
   */
  @javax.annotation.Nullable
  public AgentContextType getContextType() {
    return contextType;
  }

  public void setContextType(@javax.annotation.Nullable AgentContextType contextType) {
    this.contextType = contextType;
  }


  public AgentSendMessageRequest message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentSendMessageRequest agentSendMessageRequest = (AgentSendMessageRequest) o;
    return Objects.equals(this.contextId, agentSendMessageRequest.contextId) &&
        Objects.equals(this.contextMetadata, agentSendMessageRequest.contextMetadata) &&
        Objects.equals(this.contextType, agentSendMessageRequest.contextType) &&
        Objects.equals(this.message, agentSendMessageRequest.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contextId, contextMetadata, contextType, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentSendMessageRequest {\n");
    sb.append("    contextId: ").append(toIndentedString(contextId)).append("\n");
    sb.append("    contextMetadata: ").append(toIndentedString(contextMetadata)).append("\n");
    sb.append("    contextType: ").append(toIndentedString(contextType)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("contextId", "contextMetadata", "contextType", "message"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AgentSendMessageRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AgentSendMessageRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AgentSendMessageRequest is not found in the empty JSON string", AgentSendMessageRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AgentSendMessageRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AgentSendMessageRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("contextId") != null && !jsonObj.get("contextId").isJsonNull()) && !jsonObj.get("contextId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contextId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contextId").toString()));
      }
      if ((jsonObj.get("contextMetadata") != null && !jsonObj.get("contextMetadata").isJsonNull()) && !jsonObj.get("contextMetadata").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contextMetadata` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contextMetadata").toString()));
      }
      // validate the optional field `contextType`
      if (jsonObj.get("contextType") != null && !jsonObj.get("contextType").isJsonNull()) {
        AgentContextType.validateJsonElement(jsonObj.get("contextType"));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AgentSendMessageRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AgentSendMessageRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AgentSendMessageRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AgentSendMessageRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AgentSendMessageRequest>() {
           @Override
           public void write(JsonWriter out, AgentSendMessageRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AgentSendMessageRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AgentSendMessageRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AgentSendMessageRequest
   * @throws IOException if the JSON string is invalid with respect to AgentSendMessageRequest
   */
  public static AgentSendMessageRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AgentSendMessageRequest.class);
  }

  /**
   * Convert an instance of AgentSendMessageRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

