/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.81.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * ApplyQrcodeTemplateRequest applies a community template&#39;s design to an existing link&#39;s QR code.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ApplyQrcodeTemplateRequest {
  public static final String SERIALIZED_NAME_LINK_ID = "linkId";
  @SerializedName(SERIALIZED_NAME_LINK_ID)
  @javax.annotation.Nonnull
  private String linkId;

  public static final String SERIALIZED_NAME_TEMPLATE_SLUG = "templateSlug";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_SLUG)
  @javax.annotation.Nonnull
  private String templateSlug;

  public ApplyQrcodeTemplateRequest() {
  }

  public ApplyQrcodeTemplateRequest linkId(@javax.annotation.Nonnull String linkId) {
    this.linkId = linkId;
    return this;
  }

  /**
   * Get linkId
   * @return linkId
   */
  @javax.annotation.Nonnull
  public String getLinkId() {
    return linkId;
  }

  public void setLinkId(@javax.annotation.Nonnull String linkId) {
    this.linkId = linkId;
  }


  public ApplyQrcodeTemplateRequest templateSlug(@javax.annotation.Nonnull String templateSlug) {
    this.templateSlug = templateSlug;
    return this;
  }

  /**
   * Get templateSlug
   * @return templateSlug
   */
  @javax.annotation.Nonnull
  public String getTemplateSlug() {
    return templateSlug;
  }

  public void setTemplateSlug(@javax.annotation.Nonnull String templateSlug) {
    this.templateSlug = templateSlug;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplyQrcodeTemplateRequest applyQrcodeTemplateRequest = (ApplyQrcodeTemplateRequest) o;
    return Objects.equals(this.linkId, applyQrcodeTemplateRequest.linkId) &&
        Objects.equals(this.templateSlug, applyQrcodeTemplateRequest.templateSlug);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkId, templateSlug);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplyQrcodeTemplateRequest {\n");
    sb.append("    linkId: ").append(toIndentedString(linkId)).append("\n");
    sb.append("    templateSlug: ").append(toIndentedString(templateSlug)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("linkId", "templateSlug"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("linkId", "templateSlug"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ApplyQrcodeTemplateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApplyQrcodeTemplateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ApplyQrcodeTemplateRequest is not found in the empty JSON string", ApplyQrcodeTemplateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ApplyQrcodeTemplateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ApplyQrcodeTemplateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ApplyQrcodeTemplateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("linkId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `linkId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("linkId").toString()));
      }
      if (!jsonObj.get("templateSlug").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `templateSlug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("templateSlug").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApplyQrcodeTemplateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApplyQrcodeTemplateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApplyQrcodeTemplateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApplyQrcodeTemplateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ApplyQrcodeTemplateRequest>() {
           @Override
           public void write(JsonWriter out, ApplyQrcodeTemplateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApplyQrcodeTemplateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ApplyQrcodeTemplateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ApplyQrcodeTemplateRequest
   * @throws IOException if the JSON string is invalid with respect to ApplyQrcodeTemplateRequest
   */
  public static ApplyQrcodeTemplateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApplyQrcodeTemplateRequest.class);
  }

  /**
   * Convert an instance of ApplyQrcodeTemplateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

