/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.82.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CornersDotType
 */
@JsonAdapter(CornersDotType.Adapter.class)
public enum CornersDotType {
  
  CORNERS_DOT_TYPE_UNSPECIFIED("CORNERS_DOT_TYPE_UNSPECIFIED"),
  
  CORNERS_DOT_TYPE_DOT("CORNERS_DOT_TYPE_DOT"),
  
  CORNERS_DOT_TYPE_SQUARE("CORNERS_DOT_TYPE_SQUARE"),
  
  CORNERS_DOT_TYPE_HEXAGON("CORNERS_DOT_TYPE_HEXAGON"),
  
  CORNERS_DOT_TYPE_OCTAGON("CORNERS_DOT_TYPE_OCTAGON"),
  
  CORNERS_DOT_TYPE_TEARDROP("CORNERS_DOT_TYPE_TEARDROP"),
  
  CORNERS_DOT_TYPE_STAR("CORNERS_DOT_TYPE_STAR");

  private String value;

  CornersDotType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CornersDotType fromValue(String value) {
    for (CornersDotType b : CornersDotType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CornersDotType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CornersDotType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CornersDotType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CornersDotType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    CornersDotType.fromValue(value);
  }
}

