/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.111.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.DashboardConfig;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * CreateDashboardRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class CreateDashboardRequest {
  public static final String SERIALIZED_NAME_CONFIG = "config";
  @SerializedName(SERIALIZED_NAME_CONFIG)
  @javax.annotation.Nullable
  private DashboardConfig config;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_LINK_ID = "linkId";
  @SerializedName(SERIALIZED_NAME_LINK_ID)
  @javax.annotation.Nullable
  private String linkId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_USE_DEFAULT_WIDGETS = "useDefaultWidgets";
  @SerializedName(SERIALIZED_NAME_USE_DEFAULT_WIDGETS)
  @javax.annotation.Nullable
  private Boolean useDefaultWidgets;

  public CreateDashboardRequest() {
  }

  public CreateDashboardRequest config(@javax.annotation.Nullable DashboardConfig config) {
    this.config = config;
    return this;
  }

  /**
   * Initial widgets. Empty means the dashboard starts with none, because its contents are normally agreed with the agent before anything is created.
   * @return config
   */
  @javax.annotation.Nullable
  public DashboardConfig getConfig() {
    return config;
  }

  public void setConfig(@javax.annotation.Nullable DashboardConfig config) {
    this.config = config;
  }


  public CreateDashboardRequest id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Client-supplied dashboard id. Generated server-side when empty.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public CreateDashboardRequest linkId(@javax.annotation.Nullable String linkId) {
    this.linkId = linkId;
    return this;
  }

  /**
   * Link to scope this dashboard to. Empty creates the workspace-wide dashboard.
   * @return linkId
   */
  @javax.annotation.Nullable
  public String getLinkId() {
    return linkId;
  }

  public void setLinkId(@javax.annotation.Nullable String linkId) {
    this.linkId = linkId;
  }


  public CreateDashboardRequest name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Display name. Defaults to \&quot;Default Dashboard\&quot; when empty.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CreateDashboardRequest useDefaultWidgets(@javax.annotation.Nullable Boolean useDefaultWidgets) {
    this.useDefaultWidgets = useDefaultWidgets;
    return this;
  }

  /**
   * Fill a workspace dashboard with the standard starter widgets instead of leaving it empty. For the first dashboard in a workspace, which is created by one click rather than by a conversation. Ignored when config is set or when link_id is set, and hidden from the agent, which agrees its widgets with the user and would otherwise stack them on top of these.
   * @return useDefaultWidgets
   */
  @javax.annotation.Nullable
  public Boolean getUseDefaultWidgets() {
    return useDefaultWidgets;
  }

  public void setUseDefaultWidgets(@javax.annotation.Nullable Boolean useDefaultWidgets) {
    this.useDefaultWidgets = useDefaultWidgets;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDashboardRequest createDashboardRequest = (CreateDashboardRequest) o;
    return Objects.equals(this.config, createDashboardRequest.config) &&
        Objects.equals(this.id, createDashboardRequest.id) &&
        Objects.equals(this.linkId, createDashboardRequest.linkId) &&
        Objects.equals(this.name, createDashboardRequest.name) &&
        Objects.equals(this.useDefaultWidgets, createDashboardRequest.useDefaultWidgets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(config, id, linkId, name, useDefaultWidgets);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDashboardRequest {\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    linkId: ").append(toIndentedString(linkId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    useDefaultWidgets: ").append(toIndentedString(useDefaultWidgets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("config", "id", "linkId", "name", "useDefaultWidgets"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateDashboardRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateDashboardRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateDashboardRequest is not found in the empty JSON string", CreateDashboardRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateDashboardRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateDashboardRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `config`
      if (jsonObj.get("config") != null && !jsonObj.get("config").isJsonNull()) {
        DashboardConfig.validateJsonElement(jsonObj.get("config"));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("linkId") != null && !jsonObj.get("linkId").isJsonNull()) && !jsonObj.get("linkId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `linkId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("linkId").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateDashboardRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateDashboardRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateDashboardRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateDashboardRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateDashboardRequest>() {
           @Override
           public void write(JsonWriter out, CreateDashboardRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateDashboardRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateDashboardRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateDashboardRequest
   * @throws IOException if the JSON string is invalid with respect to CreateDashboardRequest
   */
  public static CreateDashboardRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateDashboardRequest.class);
  }

  /**
   * Convert an instance of CreateDashboardRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

