/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Defines how aggressively Linkbreakers prompts visitors for identifying data before allowing the workflow to continue.   - DATA_COLLECTION_UNSPECIFIED: Data collection preference not specified  - DATA_COLLECTION_NONE: No visitor data captured; Linkbreakers only logs the scan event.  - DATA_COLLECTION_BASIC: Minimal data prompts (e.g., email) enabled to keep friction low while identifying high-signal visitors.  - DATA_COLLECTION_ADVANCED: Full lead capture flows, including custom forms and required fields, before continuing the workflow.
 */
@JsonAdapter(DataCollection.Adapter.class)
public enum DataCollection {
  
  DATA_COLLECTION_UNSPECIFIED("DATA_COLLECTION_UNSPECIFIED"),
  
  DATA_COLLECTION_NONE("DATA_COLLECTION_NONE"),
  
  DATA_COLLECTION_BASIC("DATA_COLLECTION_BASIC"),
  
  DATA_COLLECTION_ADVANCED("DATA_COLLECTION_ADVANCED");

  private String value;

  DataCollection(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DataCollection fromValue(String value) {
    for (DataCollection b : DataCollection.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DataCollection> {
    @Override
    public void write(final JsonWriter jsonWriter, final DataCollection enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DataCollection read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DataCollection.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    DataCollection.fromValue(value);
  }
}

