/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.DeviceActorConditionTraceOption;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * DeviceActorConditionTraceData stores device actor routing metadata.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class DeviceActorConditionTraceData {
  public static final String SERIALIZED_NAME_DEVICE_ACTOR = "deviceActor";
  @SerializedName(SERIALIZED_NAME_DEVICE_ACTOR)
  @javax.annotation.Nullable
  private String deviceActor;

  public static final String SERIALIZED_NAME_HAS_ELSE = "hasElse";
  @SerializedName(SERIALIZED_NAME_HAS_ELSE)
  @javax.annotation.Nullable
  private Boolean hasElse;

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  @javax.annotation.Nullable
  private List<DeviceActorConditionTraceOption> options = new ArrayList<>();

  public DeviceActorConditionTraceData() {
  }

  public DeviceActorConditionTraceData deviceActor(@javax.annotation.Nullable String deviceActor) {
    this.deviceActor = deviceActor;
    return this;
  }

  /**
   * Get deviceActor
   * @return deviceActor
   */
  @javax.annotation.Nullable
  public String getDeviceActor() {
    return deviceActor;
  }

  public void setDeviceActor(@javax.annotation.Nullable String deviceActor) {
    this.deviceActor = deviceActor;
  }


  public DeviceActorConditionTraceData hasElse(@javax.annotation.Nullable Boolean hasElse) {
    this.hasElse = hasElse;
    return this;
  }

  /**
   * Get hasElse
   * @return hasElse
   */
  @javax.annotation.Nullable
  public Boolean getHasElse() {
    return hasElse;
  }

  public void setHasElse(@javax.annotation.Nullable Boolean hasElse) {
    this.hasElse = hasElse;
  }


  public DeviceActorConditionTraceData options(@javax.annotation.Nullable List<DeviceActorConditionTraceOption> options) {
    this.options = options;
    return this;
  }

  public DeviceActorConditionTraceData addOptionsItem(DeviceActorConditionTraceOption optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<>();
    }
    this.options.add(optionsItem);
    return this;
  }

  /**
   * Get options
   * @return options
   */
  @javax.annotation.Nullable
  public List<DeviceActorConditionTraceOption> getOptions() {
    return options;
  }

  public void setOptions(@javax.annotation.Nullable List<DeviceActorConditionTraceOption> options) {
    this.options = options;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceActorConditionTraceData deviceActorConditionTraceData = (DeviceActorConditionTraceData) o;
    return Objects.equals(this.deviceActor, deviceActorConditionTraceData.deviceActor) &&
        Objects.equals(this.hasElse, deviceActorConditionTraceData.hasElse) &&
        Objects.equals(this.options, deviceActorConditionTraceData.options);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceActor, hasElse, options);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceActorConditionTraceData {\n");
    sb.append("    deviceActor: ").append(toIndentedString(deviceActor)).append("\n");
    sb.append("    hasElse: ").append(toIndentedString(hasElse)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("deviceActor", "hasElse", "options"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeviceActorConditionTraceData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeviceActorConditionTraceData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DeviceActorConditionTraceData is not found in the empty JSON string", DeviceActorConditionTraceData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeviceActorConditionTraceData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DeviceActorConditionTraceData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("deviceActor") != null && !jsonObj.get("deviceActor").isJsonNull()) && !jsonObj.get("deviceActor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `deviceActor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deviceActor").toString()));
      }
      if (jsonObj.get("options") != null && !jsonObj.get("options").isJsonNull()) {
        JsonArray jsonArrayoptions = jsonObj.getAsJsonArray("options");
        if (jsonArrayoptions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("options").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `options` to be an array in the JSON string but got `%s`", jsonObj.get("options").toString()));
          }

          // validate the optional field `options` (array)
          for (int i = 0; i < jsonArrayoptions.size(); i++) {
            DeviceActorConditionTraceOption.validateJsonElement(jsonArrayoptions.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeviceActorConditionTraceData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeviceActorConditionTraceData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeviceActorConditionTraceData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeviceActorConditionTraceData.class));

       return (TypeAdapter<T>) new TypeAdapter<DeviceActorConditionTraceData>() {
           @Override
           public void write(JsonWriter out, DeviceActorConditionTraceData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeviceActorConditionTraceData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeviceActorConditionTraceData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeviceActorConditionTraceData
   * @throws IOException if the JSON string is invalid with respect to DeviceActorConditionTraceData
   */
  public static DeviceActorConditionTraceData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeviceActorConditionTraceData.class);
  }

  /**
   * Convert an instance of DeviceActorConditionTraceData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

