/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.144.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * - DNS_RECORD_PURPOSE_UNSPECIFIED: Not specified  - DNS_RECORD_PURPOSE_ROUTING: Sends the domain&#39;s traffic to Linkbreakers  - DNS_RECORD_PURPOSE_CERTIFICATE_DELEGATION: Lets the certificate provider issue and renew the HTTPS certificate on its own  - DNS_RECORD_PURPOSE_OWNERSHIP: Proves ownership of the domain  - DNS_RECORD_PURPOSE_CERTIFICATE_VALIDATION: Validates the certificate currently being issued
 */
@JsonAdapter(DnsRecordPurpose.Adapter.class)
public enum DnsRecordPurpose {
  
  DNS_RECORD_PURPOSE_UNSPECIFIED("DNS_RECORD_PURPOSE_UNSPECIFIED"),
  
  DNS_RECORD_PURPOSE_ROUTING("DNS_RECORD_PURPOSE_ROUTING"),
  
  DNS_RECORD_PURPOSE_CERTIFICATE_DELEGATION("DNS_RECORD_PURPOSE_CERTIFICATE_DELEGATION"),
  
  DNS_RECORD_PURPOSE_OWNERSHIP("DNS_RECORD_PURPOSE_OWNERSHIP"),
  
  DNS_RECORD_PURPOSE_CERTIFICATE_VALIDATION("DNS_RECORD_PURPOSE_CERTIFICATE_VALIDATION");

  private String value;

  DnsRecordPurpose(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DnsRecordPurpose fromValue(String value) {
    for (DnsRecordPurpose b : DnsRecordPurpose.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DnsRecordPurpose> {
    @Override
    public void write(final JsonWriter jsonWriter, final DnsRecordPurpose enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DnsRecordPurpose read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DnsRecordPurpose.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    DnsRecordPurpose.fromValue(value);
  }
}

