/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.ContactCardTraceData;
import com.linkbreakers.model.CountryConditionTraceData;
import com.linkbreakers.model.DayOfMonthConditionTraceData;
import com.linkbreakers.model.DayOfWeekConditionTraceData;
import com.linkbreakers.model.DeviceActorConditionTraceData;
import com.linkbreakers.model.DeviceBrandConditionTraceData;
import com.linkbreakers.model.DeviceBrowserConditionTraceData;
import com.linkbreakers.model.DevicePlatformConditionTraceData;
import com.linkbreakers.model.DeviceTypeConditionTraceData;
import com.linkbreakers.model.EntryAccessTraceData;
import com.linkbreakers.model.FormTraceData;
import com.linkbreakers.model.IdentifyVisitorTraceData;
import com.linkbreakers.model.MultiLinkTraceData;
import com.linkbreakers.model.PasswordTraceData;
import com.linkbreakers.model.RedirectTraceData;
import com.linkbreakers.model.SocialLinksTraceData;
import com.linkbreakers.model.SpecificDateConditionTraceData;
import com.linkbreakers.model.TimeOfDayConditionTraceData;
import com.linkbreakers.model.VisitTypeConditionTraceData;
import com.linkbreakers.model.VisitorDataConditionTraceData;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * EventTraceData captures the payload for a completed workflow step.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class EventTraceData {
  public static final String SERIALIZED_NAME_CONTACT_CARD = "contactCard";
  @SerializedName(SERIALIZED_NAME_CONTACT_CARD)
  @javax.annotation.Nullable
  private ContactCardTraceData contactCard;

  public static final String SERIALIZED_NAME_COUNTRY_CONDITION = "countryCondition";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CONDITION)
  @javax.annotation.Nullable
  private CountryConditionTraceData countryCondition;

  public static final String SERIALIZED_NAME_DAY_OF_MONTH_CONDITION = "dayOfMonthCondition";
  @SerializedName(SERIALIZED_NAME_DAY_OF_MONTH_CONDITION)
  @javax.annotation.Nullable
  private DayOfMonthConditionTraceData dayOfMonthCondition;

  public static final String SERIALIZED_NAME_DAY_OF_WEEK_CONDITION = "dayOfWeekCondition";
  @SerializedName(SERIALIZED_NAME_DAY_OF_WEEK_CONDITION)
  @javax.annotation.Nullable
  private DayOfWeekConditionTraceData dayOfWeekCondition;

  public static final String SERIALIZED_NAME_DEVICE_ACTOR_CONDITION = "deviceActorCondition";
  @SerializedName(SERIALIZED_NAME_DEVICE_ACTOR_CONDITION)
  @javax.annotation.Nullable
  private DeviceActorConditionTraceData deviceActorCondition;

  public static final String SERIALIZED_NAME_DEVICE_BRAND_CONDITION = "deviceBrandCondition";
  @SerializedName(SERIALIZED_NAME_DEVICE_BRAND_CONDITION)
  @javax.annotation.Nullable
  private DeviceBrandConditionTraceData deviceBrandCondition;

  public static final String SERIALIZED_NAME_DEVICE_BROWSER_CONDITION = "deviceBrowserCondition";
  @SerializedName(SERIALIZED_NAME_DEVICE_BROWSER_CONDITION)
  @javax.annotation.Nullable
  private DeviceBrowserConditionTraceData deviceBrowserCondition;

  public static final String SERIALIZED_NAME_DEVICE_PLATFORM_CONDITION = "devicePlatformCondition";
  @SerializedName(SERIALIZED_NAME_DEVICE_PLATFORM_CONDITION)
  @javax.annotation.Nullable
  private DevicePlatformConditionTraceData devicePlatformCondition;

  public static final String SERIALIZED_NAME_DEVICE_TYPE_CONDITION = "deviceTypeCondition";
  @SerializedName(SERIALIZED_NAME_DEVICE_TYPE_CONDITION)
  @javax.annotation.Nullable
  private DeviceTypeConditionTraceData deviceTypeCondition;

  public static final String SERIALIZED_NAME_ENTRY_ACCESS = "entryAccess";
  @SerializedName(SERIALIZED_NAME_ENTRY_ACCESS)
  @javax.annotation.Nullable
  private EntryAccessTraceData entryAccess;

  public static final String SERIALIZED_NAME_FORM = "form";
  @SerializedName(SERIALIZED_NAME_FORM)
  @javax.annotation.Nullable
  private FormTraceData form;

  public static final String SERIALIZED_NAME_IDENTIFY_VISITOR = "identifyVisitor";
  @SerializedName(SERIALIZED_NAME_IDENTIFY_VISITOR)
  @javax.annotation.Nullable
  private IdentifyVisitorTraceData identifyVisitor;

  public static final String SERIALIZED_NAME_MULTI_LINK = "multiLink";
  @SerializedName(SERIALIZED_NAME_MULTI_LINK)
  @javax.annotation.Nullable
  private MultiLinkTraceData multiLink;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  @javax.annotation.Nullable
  private PasswordTraceData password;

  public static final String SERIALIZED_NAME_REDIRECT = "redirect";
  @SerializedName(SERIALIZED_NAME_REDIRECT)
  @javax.annotation.Nullable
  private RedirectTraceData redirect;

  public static final String SERIALIZED_NAME_SOCIAL_LINKS = "socialLinks";
  @SerializedName(SERIALIZED_NAME_SOCIAL_LINKS)
  @javax.annotation.Nullable
  private SocialLinksTraceData socialLinks;

  public static final String SERIALIZED_NAME_SPECIFIC_DATE_CONDITION = "specificDateCondition";
  @SerializedName(SERIALIZED_NAME_SPECIFIC_DATE_CONDITION)
  @javax.annotation.Nullable
  private SpecificDateConditionTraceData specificDateCondition;

  public static final String SERIALIZED_NAME_TIME_OF_DAY_CONDITION = "timeOfDayCondition";
  @SerializedName(SERIALIZED_NAME_TIME_OF_DAY_CONDITION)
  @javax.annotation.Nullable
  private TimeOfDayConditionTraceData timeOfDayCondition;

  public static final String SERIALIZED_NAME_VISIT_TYPE_CONDITION = "visitTypeCondition";
  @SerializedName(SERIALIZED_NAME_VISIT_TYPE_CONDITION)
  @javax.annotation.Nullable
  private VisitTypeConditionTraceData visitTypeCondition;

  public static final String SERIALIZED_NAME_VISITOR_DATA_CONDITION = "visitorDataCondition";
  @SerializedName(SERIALIZED_NAME_VISITOR_DATA_CONDITION)
  @javax.annotation.Nullable
  private VisitorDataConditionTraceData visitorDataCondition;

  public EventTraceData() {
  }

  public EventTraceData contactCard(@javax.annotation.Nullable ContactCardTraceData contactCard) {
    this.contactCard = contactCard;
    return this;
  }

  /**
   * Get contactCard
   * @return contactCard
   */
  @javax.annotation.Nullable
  public ContactCardTraceData getContactCard() {
    return contactCard;
  }

  public void setContactCard(@javax.annotation.Nullable ContactCardTraceData contactCard) {
    this.contactCard = contactCard;
  }


  public EventTraceData countryCondition(@javax.annotation.Nullable CountryConditionTraceData countryCondition) {
    this.countryCondition = countryCondition;
    return this;
  }

  /**
   * Get countryCondition
   * @return countryCondition
   */
  @javax.annotation.Nullable
  public CountryConditionTraceData getCountryCondition() {
    return countryCondition;
  }

  public void setCountryCondition(@javax.annotation.Nullable CountryConditionTraceData countryCondition) {
    this.countryCondition = countryCondition;
  }


  public EventTraceData dayOfMonthCondition(@javax.annotation.Nullable DayOfMonthConditionTraceData dayOfMonthCondition) {
    this.dayOfMonthCondition = dayOfMonthCondition;
    return this;
  }

  /**
   * Get dayOfMonthCondition
   * @return dayOfMonthCondition
   */
  @javax.annotation.Nullable
  public DayOfMonthConditionTraceData getDayOfMonthCondition() {
    return dayOfMonthCondition;
  }

  public void setDayOfMonthCondition(@javax.annotation.Nullable DayOfMonthConditionTraceData dayOfMonthCondition) {
    this.dayOfMonthCondition = dayOfMonthCondition;
  }


  public EventTraceData dayOfWeekCondition(@javax.annotation.Nullable DayOfWeekConditionTraceData dayOfWeekCondition) {
    this.dayOfWeekCondition = dayOfWeekCondition;
    return this;
  }

  /**
   * Get dayOfWeekCondition
   * @return dayOfWeekCondition
   */
  @javax.annotation.Nullable
  public DayOfWeekConditionTraceData getDayOfWeekCondition() {
    return dayOfWeekCondition;
  }

  public void setDayOfWeekCondition(@javax.annotation.Nullable DayOfWeekConditionTraceData dayOfWeekCondition) {
    this.dayOfWeekCondition = dayOfWeekCondition;
  }


  public EventTraceData deviceActorCondition(@javax.annotation.Nullable DeviceActorConditionTraceData deviceActorCondition) {
    this.deviceActorCondition = deviceActorCondition;
    return this;
  }

  /**
   * Get deviceActorCondition
   * @return deviceActorCondition
   */
  @javax.annotation.Nullable
  public DeviceActorConditionTraceData getDeviceActorCondition() {
    return deviceActorCondition;
  }

  public void setDeviceActorCondition(@javax.annotation.Nullable DeviceActorConditionTraceData deviceActorCondition) {
    this.deviceActorCondition = deviceActorCondition;
  }


  public EventTraceData deviceBrandCondition(@javax.annotation.Nullable DeviceBrandConditionTraceData deviceBrandCondition) {
    this.deviceBrandCondition = deviceBrandCondition;
    return this;
  }

  /**
   * Get deviceBrandCondition
   * @return deviceBrandCondition
   */
  @javax.annotation.Nullable
  public DeviceBrandConditionTraceData getDeviceBrandCondition() {
    return deviceBrandCondition;
  }

  public void setDeviceBrandCondition(@javax.annotation.Nullable DeviceBrandConditionTraceData deviceBrandCondition) {
    this.deviceBrandCondition = deviceBrandCondition;
  }


  public EventTraceData deviceBrowserCondition(@javax.annotation.Nullable DeviceBrowserConditionTraceData deviceBrowserCondition) {
    this.deviceBrowserCondition = deviceBrowserCondition;
    return this;
  }

  /**
   * Get deviceBrowserCondition
   * @return deviceBrowserCondition
   */
  @javax.annotation.Nullable
  public DeviceBrowserConditionTraceData getDeviceBrowserCondition() {
    return deviceBrowserCondition;
  }

  public void setDeviceBrowserCondition(@javax.annotation.Nullable DeviceBrowserConditionTraceData deviceBrowserCondition) {
    this.deviceBrowserCondition = deviceBrowserCondition;
  }


  public EventTraceData devicePlatformCondition(@javax.annotation.Nullable DevicePlatformConditionTraceData devicePlatformCondition) {
    this.devicePlatformCondition = devicePlatformCondition;
    return this;
  }

  /**
   * Get devicePlatformCondition
   * @return devicePlatformCondition
   */
  @javax.annotation.Nullable
  public DevicePlatformConditionTraceData getDevicePlatformCondition() {
    return devicePlatformCondition;
  }

  public void setDevicePlatformCondition(@javax.annotation.Nullable DevicePlatformConditionTraceData devicePlatformCondition) {
    this.devicePlatformCondition = devicePlatformCondition;
  }


  public EventTraceData deviceTypeCondition(@javax.annotation.Nullable DeviceTypeConditionTraceData deviceTypeCondition) {
    this.deviceTypeCondition = deviceTypeCondition;
    return this;
  }

  /**
   * Get deviceTypeCondition
   * @return deviceTypeCondition
   */
  @javax.annotation.Nullable
  public DeviceTypeConditionTraceData getDeviceTypeCondition() {
    return deviceTypeCondition;
  }

  public void setDeviceTypeCondition(@javax.annotation.Nullable DeviceTypeConditionTraceData deviceTypeCondition) {
    this.deviceTypeCondition = deviceTypeCondition;
  }


  public EventTraceData entryAccess(@javax.annotation.Nullable EntryAccessTraceData entryAccess) {
    this.entryAccess = entryAccess;
    return this;
  }

  /**
   * Get entryAccess
   * @return entryAccess
   */
  @javax.annotation.Nullable
  public EntryAccessTraceData getEntryAccess() {
    return entryAccess;
  }

  public void setEntryAccess(@javax.annotation.Nullable EntryAccessTraceData entryAccess) {
    this.entryAccess = entryAccess;
  }


  public EventTraceData form(@javax.annotation.Nullable FormTraceData form) {
    this.form = form;
    return this;
  }

  /**
   * Get form
   * @return form
   */
  @javax.annotation.Nullable
  public FormTraceData getForm() {
    return form;
  }

  public void setForm(@javax.annotation.Nullable FormTraceData form) {
    this.form = form;
  }


  public EventTraceData identifyVisitor(@javax.annotation.Nullable IdentifyVisitorTraceData identifyVisitor) {
    this.identifyVisitor = identifyVisitor;
    return this;
  }

  /**
   * Get identifyVisitor
   * @return identifyVisitor
   */
  @javax.annotation.Nullable
  public IdentifyVisitorTraceData getIdentifyVisitor() {
    return identifyVisitor;
  }

  public void setIdentifyVisitor(@javax.annotation.Nullable IdentifyVisitorTraceData identifyVisitor) {
    this.identifyVisitor = identifyVisitor;
  }


  public EventTraceData multiLink(@javax.annotation.Nullable MultiLinkTraceData multiLink) {
    this.multiLink = multiLink;
    return this;
  }

  /**
   * Get multiLink
   * @return multiLink
   */
  @javax.annotation.Nullable
  public MultiLinkTraceData getMultiLink() {
    return multiLink;
  }

  public void setMultiLink(@javax.annotation.Nullable MultiLinkTraceData multiLink) {
    this.multiLink = multiLink;
  }


  public EventTraceData password(@javax.annotation.Nullable PasswordTraceData password) {
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @javax.annotation.Nullable
  public PasswordTraceData getPassword() {
    return password;
  }

  public void setPassword(@javax.annotation.Nullable PasswordTraceData password) {
    this.password = password;
  }


  public EventTraceData redirect(@javax.annotation.Nullable RedirectTraceData redirect) {
    this.redirect = redirect;
    return this;
  }

  /**
   * Get redirect
   * @return redirect
   */
  @javax.annotation.Nullable
  public RedirectTraceData getRedirect() {
    return redirect;
  }

  public void setRedirect(@javax.annotation.Nullable RedirectTraceData redirect) {
    this.redirect = redirect;
  }


  public EventTraceData socialLinks(@javax.annotation.Nullable SocialLinksTraceData socialLinks) {
    this.socialLinks = socialLinks;
    return this;
  }

  /**
   * Get socialLinks
   * @return socialLinks
   */
  @javax.annotation.Nullable
  public SocialLinksTraceData getSocialLinks() {
    return socialLinks;
  }

  public void setSocialLinks(@javax.annotation.Nullable SocialLinksTraceData socialLinks) {
    this.socialLinks = socialLinks;
  }


  public EventTraceData specificDateCondition(@javax.annotation.Nullable SpecificDateConditionTraceData specificDateCondition) {
    this.specificDateCondition = specificDateCondition;
    return this;
  }

  /**
   * Get specificDateCondition
   * @return specificDateCondition
   */
  @javax.annotation.Nullable
  public SpecificDateConditionTraceData getSpecificDateCondition() {
    return specificDateCondition;
  }

  public void setSpecificDateCondition(@javax.annotation.Nullable SpecificDateConditionTraceData specificDateCondition) {
    this.specificDateCondition = specificDateCondition;
  }


  public EventTraceData timeOfDayCondition(@javax.annotation.Nullable TimeOfDayConditionTraceData timeOfDayCondition) {
    this.timeOfDayCondition = timeOfDayCondition;
    return this;
  }

  /**
   * Get timeOfDayCondition
   * @return timeOfDayCondition
   */
  @javax.annotation.Nullable
  public TimeOfDayConditionTraceData getTimeOfDayCondition() {
    return timeOfDayCondition;
  }

  public void setTimeOfDayCondition(@javax.annotation.Nullable TimeOfDayConditionTraceData timeOfDayCondition) {
    this.timeOfDayCondition = timeOfDayCondition;
  }


  public EventTraceData visitTypeCondition(@javax.annotation.Nullable VisitTypeConditionTraceData visitTypeCondition) {
    this.visitTypeCondition = visitTypeCondition;
    return this;
  }

  /**
   * Get visitTypeCondition
   * @return visitTypeCondition
   */
  @javax.annotation.Nullable
  public VisitTypeConditionTraceData getVisitTypeCondition() {
    return visitTypeCondition;
  }

  public void setVisitTypeCondition(@javax.annotation.Nullable VisitTypeConditionTraceData visitTypeCondition) {
    this.visitTypeCondition = visitTypeCondition;
  }


  public EventTraceData visitorDataCondition(@javax.annotation.Nullable VisitorDataConditionTraceData visitorDataCondition) {
    this.visitorDataCondition = visitorDataCondition;
    return this;
  }

  /**
   * Get visitorDataCondition
   * @return visitorDataCondition
   */
  @javax.annotation.Nullable
  public VisitorDataConditionTraceData getVisitorDataCondition() {
    return visitorDataCondition;
  }

  public void setVisitorDataCondition(@javax.annotation.Nullable VisitorDataConditionTraceData visitorDataCondition) {
    this.visitorDataCondition = visitorDataCondition;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventTraceData eventTraceData = (EventTraceData) o;
    return Objects.equals(this.contactCard, eventTraceData.contactCard) &&
        Objects.equals(this.countryCondition, eventTraceData.countryCondition) &&
        Objects.equals(this.dayOfMonthCondition, eventTraceData.dayOfMonthCondition) &&
        Objects.equals(this.dayOfWeekCondition, eventTraceData.dayOfWeekCondition) &&
        Objects.equals(this.deviceActorCondition, eventTraceData.deviceActorCondition) &&
        Objects.equals(this.deviceBrandCondition, eventTraceData.deviceBrandCondition) &&
        Objects.equals(this.deviceBrowserCondition, eventTraceData.deviceBrowserCondition) &&
        Objects.equals(this.devicePlatformCondition, eventTraceData.devicePlatformCondition) &&
        Objects.equals(this.deviceTypeCondition, eventTraceData.deviceTypeCondition) &&
        Objects.equals(this.entryAccess, eventTraceData.entryAccess) &&
        Objects.equals(this.form, eventTraceData.form) &&
        Objects.equals(this.identifyVisitor, eventTraceData.identifyVisitor) &&
        Objects.equals(this.multiLink, eventTraceData.multiLink) &&
        Objects.equals(this.password, eventTraceData.password) &&
        Objects.equals(this.redirect, eventTraceData.redirect) &&
        Objects.equals(this.socialLinks, eventTraceData.socialLinks) &&
        Objects.equals(this.specificDateCondition, eventTraceData.specificDateCondition) &&
        Objects.equals(this.timeOfDayCondition, eventTraceData.timeOfDayCondition) &&
        Objects.equals(this.visitTypeCondition, eventTraceData.visitTypeCondition) &&
        Objects.equals(this.visitorDataCondition, eventTraceData.visitorDataCondition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactCard, countryCondition, dayOfMonthCondition, dayOfWeekCondition, deviceActorCondition, deviceBrandCondition, deviceBrowserCondition, devicePlatformCondition, deviceTypeCondition, entryAccess, form, identifyVisitor, multiLink, password, redirect, socialLinks, specificDateCondition, timeOfDayCondition, visitTypeCondition, visitorDataCondition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventTraceData {\n");
    sb.append("    contactCard: ").append(toIndentedString(contactCard)).append("\n");
    sb.append("    countryCondition: ").append(toIndentedString(countryCondition)).append("\n");
    sb.append("    dayOfMonthCondition: ").append(toIndentedString(dayOfMonthCondition)).append("\n");
    sb.append("    dayOfWeekCondition: ").append(toIndentedString(dayOfWeekCondition)).append("\n");
    sb.append("    deviceActorCondition: ").append(toIndentedString(deviceActorCondition)).append("\n");
    sb.append("    deviceBrandCondition: ").append(toIndentedString(deviceBrandCondition)).append("\n");
    sb.append("    deviceBrowserCondition: ").append(toIndentedString(deviceBrowserCondition)).append("\n");
    sb.append("    devicePlatformCondition: ").append(toIndentedString(devicePlatformCondition)).append("\n");
    sb.append("    deviceTypeCondition: ").append(toIndentedString(deviceTypeCondition)).append("\n");
    sb.append("    entryAccess: ").append(toIndentedString(entryAccess)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    identifyVisitor: ").append(toIndentedString(identifyVisitor)).append("\n");
    sb.append("    multiLink: ").append(toIndentedString(multiLink)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    redirect: ").append(toIndentedString(redirect)).append("\n");
    sb.append("    socialLinks: ").append(toIndentedString(socialLinks)).append("\n");
    sb.append("    specificDateCondition: ").append(toIndentedString(specificDateCondition)).append("\n");
    sb.append("    timeOfDayCondition: ").append(toIndentedString(timeOfDayCondition)).append("\n");
    sb.append("    visitTypeCondition: ").append(toIndentedString(visitTypeCondition)).append("\n");
    sb.append("    visitorDataCondition: ").append(toIndentedString(visitorDataCondition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("contactCard", "countryCondition", "dayOfMonthCondition", "dayOfWeekCondition", "deviceActorCondition", "deviceBrandCondition", "deviceBrowserCondition", "devicePlatformCondition", "deviceTypeCondition", "entryAccess", "form", "identifyVisitor", "multiLink", "password", "redirect", "socialLinks", "specificDateCondition", "timeOfDayCondition", "visitTypeCondition", "visitorDataCondition"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EventTraceData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EventTraceData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EventTraceData is not found in the empty JSON string", EventTraceData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EventTraceData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EventTraceData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `contactCard`
      if (jsonObj.get("contactCard") != null && !jsonObj.get("contactCard").isJsonNull()) {
        ContactCardTraceData.validateJsonElement(jsonObj.get("contactCard"));
      }
      // validate the optional field `countryCondition`
      if (jsonObj.get("countryCondition") != null && !jsonObj.get("countryCondition").isJsonNull()) {
        CountryConditionTraceData.validateJsonElement(jsonObj.get("countryCondition"));
      }
      // validate the optional field `dayOfMonthCondition`
      if (jsonObj.get("dayOfMonthCondition") != null && !jsonObj.get("dayOfMonthCondition").isJsonNull()) {
        DayOfMonthConditionTraceData.validateJsonElement(jsonObj.get("dayOfMonthCondition"));
      }
      // validate the optional field `dayOfWeekCondition`
      if (jsonObj.get("dayOfWeekCondition") != null && !jsonObj.get("dayOfWeekCondition").isJsonNull()) {
        DayOfWeekConditionTraceData.validateJsonElement(jsonObj.get("dayOfWeekCondition"));
      }
      // validate the optional field `deviceActorCondition`
      if (jsonObj.get("deviceActorCondition") != null && !jsonObj.get("deviceActorCondition").isJsonNull()) {
        DeviceActorConditionTraceData.validateJsonElement(jsonObj.get("deviceActorCondition"));
      }
      // validate the optional field `deviceBrandCondition`
      if (jsonObj.get("deviceBrandCondition") != null && !jsonObj.get("deviceBrandCondition").isJsonNull()) {
        DeviceBrandConditionTraceData.validateJsonElement(jsonObj.get("deviceBrandCondition"));
      }
      // validate the optional field `deviceBrowserCondition`
      if (jsonObj.get("deviceBrowserCondition") != null && !jsonObj.get("deviceBrowserCondition").isJsonNull()) {
        DeviceBrowserConditionTraceData.validateJsonElement(jsonObj.get("deviceBrowserCondition"));
      }
      // validate the optional field `devicePlatformCondition`
      if (jsonObj.get("devicePlatformCondition") != null && !jsonObj.get("devicePlatformCondition").isJsonNull()) {
        DevicePlatformConditionTraceData.validateJsonElement(jsonObj.get("devicePlatformCondition"));
      }
      // validate the optional field `deviceTypeCondition`
      if (jsonObj.get("deviceTypeCondition") != null && !jsonObj.get("deviceTypeCondition").isJsonNull()) {
        DeviceTypeConditionTraceData.validateJsonElement(jsonObj.get("deviceTypeCondition"));
      }
      // validate the optional field `entryAccess`
      if (jsonObj.get("entryAccess") != null && !jsonObj.get("entryAccess").isJsonNull()) {
        EntryAccessTraceData.validateJsonElement(jsonObj.get("entryAccess"));
      }
      // validate the optional field `form`
      if (jsonObj.get("form") != null && !jsonObj.get("form").isJsonNull()) {
        FormTraceData.validateJsonElement(jsonObj.get("form"));
      }
      // validate the optional field `identifyVisitor`
      if (jsonObj.get("identifyVisitor") != null && !jsonObj.get("identifyVisitor").isJsonNull()) {
        IdentifyVisitorTraceData.validateJsonElement(jsonObj.get("identifyVisitor"));
      }
      // validate the optional field `multiLink`
      if (jsonObj.get("multiLink") != null && !jsonObj.get("multiLink").isJsonNull()) {
        MultiLinkTraceData.validateJsonElement(jsonObj.get("multiLink"));
      }
      // validate the optional field `password`
      if (jsonObj.get("password") != null && !jsonObj.get("password").isJsonNull()) {
        PasswordTraceData.validateJsonElement(jsonObj.get("password"));
      }
      // validate the optional field `redirect`
      if (jsonObj.get("redirect") != null && !jsonObj.get("redirect").isJsonNull()) {
        RedirectTraceData.validateJsonElement(jsonObj.get("redirect"));
      }
      // validate the optional field `socialLinks`
      if (jsonObj.get("socialLinks") != null && !jsonObj.get("socialLinks").isJsonNull()) {
        SocialLinksTraceData.validateJsonElement(jsonObj.get("socialLinks"));
      }
      // validate the optional field `specificDateCondition`
      if (jsonObj.get("specificDateCondition") != null && !jsonObj.get("specificDateCondition").isJsonNull()) {
        SpecificDateConditionTraceData.validateJsonElement(jsonObj.get("specificDateCondition"));
      }
      // validate the optional field `timeOfDayCondition`
      if (jsonObj.get("timeOfDayCondition") != null && !jsonObj.get("timeOfDayCondition").isJsonNull()) {
        TimeOfDayConditionTraceData.validateJsonElement(jsonObj.get("timeOfDayCondition"));
      }
      // validate the optional field `visitTypeCondition`
      if (jsonObj.get("visitTypeCondition") != null && !jsonObj.get("visitTypeCondition").isJsonNull()) {
        VisitTypeConditionTraceData.validateJsonElement(jsonObj.get("visitTypeCondition"));
      }
      // validate the optional field `visitorDataCondition`
      if (jsonObj.get("visitorDataCondition") != null && !jsonObj.get("visitorDataCondition").isJsonNull()) {
        VisitorDataConditionTraceData.validateJsonElement(jsonObj.get("visitorDataCondition"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EventTraceData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EventTraceData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EventTraceData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EventTraceData.class));

       return (TypeAdapter<T>) new TypeAdapter<EventTraceData>() {
           @Override
           public void write(JsonWriter out, EventTraceData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EventTraceData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EventTraceData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EventTraceData
   * @throws IOException if the JSON string is invalid with respect to EventTraceData
   */
  public static EventTraceData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EventTraceData.class);
  }

  /**
   * Convert an instance of EventTraceData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

