/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * Aggregated analytics calculated on demand for time windows, giving Linkbreakers UIs headline numbers without exposing raw events.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class EventsMetric {
  public static final String SERIALIZED_NAME_AVERAGE_LEAD_SCORE = "averageLeadScore";
  @SerializedName(SERIALIZED_NAME_AVERAGE_LEAD_SCORE)
  @javax.annotation.Nullable
  private Double averageLeadScore;

  public static final String SERIALIZED_NAME_FIRST_AT = "firstAt";
  @SerializedName(SERIALIZED_NAME_FIRST_AT)
  @javax.annotation.Nullable
  private OffsetDateTime firstAt;

  public static final String SERIALIZED_NAME_LAST_AT = "lastAt";
  @SerializedName(SERIALIZED_NAME_LAST_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lastAt;

  public static final String SERIALIZED_NAME_TOP_CITY = "topCity";
  @SerializedName(SERIALIZED_NAME_TOP_CITY)
  @javax.annotation.Nullable
  private String topCity;

  public static final String SERIALIZED_NAME_TOP_COUNTRY = "topCountry";
  @SerializedName(SERIALIZED_NAME_TOP_COUNTRY)
  @javax.annotation.Nullable
  private String topCountry;

  /**
   * DeviceType represents the physical form factor of the device. This describes the hardware category (phone, tablet, laptop, etc.), NOT who or what is operating it — see DeviceActor for that.   - DEVICE_TYPE_UNSPECIFIED: Device type not specified or not yet detected  - DEVICE_TYPE_NATIVE: Native QR scanner (no browser capabilities reported)  - DEVICE_TYPE_MOBILE: Mobile handset browser  - DEVICE_TYPE_TABLET: Tablet browser  - DEVICE_TYPE_DESKTOP: Desktop or laptop browser  - DEVICE_TYPE_UNKNOWN: Unable to classify the device
   */
  @JsonAdapter(TopDeviceTypeEnum.Adapter.class)
  public enum TopDeviceTypeEnum {
    DEVICE_TYPE_UNSPECIFIED("DEVICE_TYPE_UNSPECIFIED"),
    
    DEVICE_TYPE_NATIVE("DEVICE_TYPE_NATIVE"),
    
    DEVICE_TYPE_MOBILE("DEVICE_TYPE_MOBILE"),
    
    DEVICE_TYPE_TABLET("DEVICE_TYPE_TABLET"),
    
    DEVICE_TYPE_DESKTOP("DEVICE_TYPE_DESKTOP"),
    
    DEVICE_TYPE_UNKNOWN("DEVICE_TYPE_UNKNOWN");

    private String value;

    TopDeviceTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TopDeviceTypeEnum fromValue(String value) {
      for (TopDeviceTypeEnum b : TopDeviceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TopDeviceTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TopDeviceTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TopDeviceTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TopDeviceTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TopDeviceTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TOP_DEVICE_TYPE = "topDeviceType";
  @SerializedName(SERIALIZED_NAME_TOP_DEVICE_TYPE)
  @javax.annotation.Nullable
  private TopDeviceTypeEnum topDeviceType;

  public static final String SERIALIZED_NAME_TOTAL_CITIES = "totalCities";
  @SerializedName(SERIALIZED_NAME_TOTAL_CITIES)
  @javax.annotation.Nullable
  private Integer totalCities;

  public static final String SERIALIZED_NAME_TOTAL_COUNTRIES = "totalCountries";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNTRIES)
  @javax.annotation.Nullable
  private Integer totalCountries;

  public static final String SERIALIZED_NAME_TOTAL_DEVICE_TYPES = "totalDeviceTypes";
  @SerializedName(SERIALIZED_NAME_TOTAL_DEVICE_TYPES)
  @javax.annotation.Nullable
  private Integer totalDeviceTypes;

  public static final String SERIALIZED_NAME_TOTAL_EVENTS = "totalEvents";
  @SerializedName(SERIALIZED_NAME_TOTAL_EVENTS)
  @javax.annotation.Nullable
  private Integer totalEvents;

  public EventsMetric() {
  }

  public EventsMetric averageLeadScore(@javax.annotation.Nullable Double averageLeadScore) {
    this.averageLeadScore = averageLeadScore;
    return this;
  }

  /**
   * Get averageLeadScore
   * @return averageLeadScore
   */
  @javax.annotation.Nullable
  public Double getAverageLeadScore() {
    return averageLeadScore;
  }

  public void setAverageLeadScore(@javax.annotation.Nullable Double averageLeadScore) {
    this.averageLeadScore = averageLeadScore;
  }


  public EventsMetric firstAt(@javax.annotation.Nullable OffsetDateTime firstAt) {
    this.firstAt = firstAt;
    return this;
  }

  /**
   * Get firstAt
   * @return firstAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getFirstAt() {
    return firstAt;
  }

  public void setFirstAt(@javax.annotation.Nullable OffsetDateTime firstAt) {
    this.firstAt = firstAt;
  }


  public EventsMetric lastAt(@javax.annotation.Nullable OffsetDateTime lastAt) {
    this.lastAt = lastAt;
    return this;
  }

  /**
   * Get lastAt
   * @return lastAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastAt() {
    return lastAt;
  }

  public void setLastAt(@javax.annotation.Nullable OffsetDateTime lastAt) {
    this.lastAt = lastAt;
  }


  public EventsMetric topCity(@javax.annotation.Nullable String topCity) {
    this.topCity = topCity;
    return this;
  }

  /**
   * Get topCity
   * @return topCity
   */
  @javax.annotation.Nullable
  public String getTopCity() {
    return topCity;
  }

  public void setTopCity(@javax.annotation.Nullable String topCity) {
    this.topCity = topCity;
  }


  public EventsMetric topCountry(@javax.annotation.Nullable String topCountry) {
    this.topCountry = topCountry;
    return this;
  }

  /**
   * Get topCountry
   * @return topCountry
   */
  @javax.annotation.Nullable
  public String getTopCountry() {
    return topCountry;
  }

  public void setTopCountry(@javax.annotation.Nullable String topCountry) {
    this.topCountry = topCountry;
  }


  public EventsMetric topDeviceType(@javax.annotation.Nullable TopDeviceTypeEnum topDeviceType) {
    this.topDeviceType = topDeviceType;
    return this;
  }

  /**
   * DeviceType represents the physical form factor of the device. This describes the hardware category (phone, tablet, laptop, etc.), NOT who or what is operating it — see DeviceActor for that.   - DEVICE_TYPE_UNSPECIFIED: Device type not specified or not yet detected  - DEVICE_TYPE_NATIVE: Native QR scanner (no browser capabilities reported)  - DEVICE_TYPE_MOBILE: Mobile handset browser  - DEVICE_TYPE_TABLET: Tablet browser  - DEVICE_TYPE_DESKTOP: Desktop or laptop browser  - DEVICE_TYPE_UNKNOWN: Unable to classify the device
   * @return topDeviceType
   */
  @javax.annotation.Nullable
  public TopDeviceTypeEnum getTopDeviceType() {
    return topDeviceType;
  }

  public void setTopDeviceType(@javax.annotation.Nullable TopDeviceTypeEnum topDeviceType) {
    this.topDeviceType = topDeviceType;
  }


  public EventsMetric totalCities(@javax.annotation.Nullable Integer totalCities) {
    this.totalCities = totalCities;
    return this;
  }

  /**
   * Get totalCities
   * @return totalCities
   */
  @javax.annotation.Nullable
  public Integer getTotalCities() {
    return totalCities;
  }

  public void setTotalCities(@javax.annotation.Nullable Integer totalCities) {
    this.totalCities = totalCities;
  }


  public EventsMetric totalCountries(@javax.annotation.Nullable Integer totalCountries) {
    this.totalCountries = totalCountries;
    return this;
  }

  /**
   * Get totalCountries
   * @return totalCountries
   */
  @javax.annotation.Nullable
  public Integer getTotalCountries() {
    return totalCountries;
  }

  public void setTotalCountries(@javax.annotation.Nullable Integer totalCountries) {
    this.totalCountries = totalCountries;
  }


  public EventsMetric totalDeviceTypes(@javax.annotation.Nullable Integer totalDeviceTypes) {
    this.totalDeviceTypes = totalDeviceTypes;
    return this;
  }

  /**
   * Get totalDeviceTypes
   * @return totalDeviceTypes
   */
  @javax.annotation.Nullable
  public Integer getTotalDeviceTypes() {
    return totalDeviceTypes;
  }

  public void setTotalDeviceTypes(@javax.annotation.Nullable Integer totalDeviceTypes) {
    this.totalDeviceTypes = totalDeviceTypes;
  }


  public EventsMetric totalEvents(@javax.annotation.Nullable Integer totalEvents) {
    this.totalEvents = totalEvents;
    return this;
  }

  /**
   * Get totalEvents
   * @return totalEvents
   */
  @javax.annotation.Nullable
  public Integer getTotalEvents() {
    return totalEvents;
  }

  public void setTotalEvents(@javax.annotation.Nullable Integer totalEvents) {
    this.totalEvents = totalEvents;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventsMetric eventsMetric = (EventsMetric) o;
    return Objects.equals(this.averageLeadScore, eventsMetric.averageLeadScore) &&
        Objects.equals(this.firstAt, eventsMetric.firstAt) &&
        Objects.equals(this.lastAt, eventsMetric.lastAt) &&
        Objects.equals(this.topCity, eventsMetric.topCity) &&
        Objects.equals(this.topCountry, eventsMetric.topCountry) &&
        Objects.equals(this.topDeviceType, eventsMetric.topDeviceType) &&
        Objects.equals(this.totalCities, eventsMetric.totalCities) &&
        Objects.equals(this.totalCountries, eventsMetric.totalCountries) &&
        Objects.equals(this.totalDeviceTypes, eventsMetric.totalDeviceTypes) &&
        Objects.equals(this.totalEvents, eventsMetric.totalEvents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(averageLeadScore, firstAt, lastAt, topCity, topCountry, topDeviceType, totalCities, totalCountries, totalDeviceTypes, totalEvents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventsMetric {\n");
    sb.append("    averageLeadScore: ").append(toIndentedString(averageLeadScore)).append("\n");
    sb.append("    firstAt: ").append(toIndentedString(firstAt)).append("\n");
    sb.append("    lastAt: ").append(toIndentedString(lastAt)).append("\n");
    sb.append("    topCity: ").append(toIndentedString(topCity)).append("\n");
    sb.append("    topCountry: ").append(toIndentedString(topCountry)).append("\n");
    sb.append("    topDeviceType: ").append(toIndentedString(topDeviceType)).append("\n");
    sb.append("    totalCities: ").append(toIndentedString(totalCities)).append("\n");
    sb.append("    totalCountries: ").append(toIndentedString(totalCountries)).append("\n");
    sb.append("    totalDeviceTypes: ").append(toIndentedString(totalDeviceTypes)).append("\n");
    sb.append("    totalEvents: ").append(toIndentedString(totalEvents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("averageLeadScore", "firstAt", "lastAt", "topCity", "topCountry", "topDeviceType", "totalCities", "totalCountries", "totalDeviceTypes", "totalEvents"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EventsMetric
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EventsMetric.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EventsMetric is not found in the empty JSON string", EventsMetric.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EventsMetric.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EventsMetric` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("topCity") != null && !jsonObj.get("topCity").isJsonNull()) && !jsonObj.get("topCity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `topCity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("topCity").toString()));
      }
      if ((jsonObj.get("topCountry") != null && !jsonObj.get("topCountry").isJsonNull()) && !jsonObj.get("topCountry").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `topCountry` to be a primitive type in the JSON string but got `%s`", jsonObj.get("topCountry").toString()));
      }
      if ((jsonObj.get("topDeviceType") != null && !jsonObj.get("topDeviceType").isJsonNull()) && !jsonObj.get("topDeviceType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `topDeviceType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("topDeviceType").toString()));
      }
      // validate the optional field `topDeviceType`
      if (jsonObj.get("topDeviceType") != null && !jsonObj.get("topDeviceType").isJsonNull()) {
        TopDeviceTypeEnum.validateJsonElement(jsonObj.get("topDeviceType"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EventsMetric.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EventsMetric' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EventsMetric> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EventsMetric.class));

       return (TypeAdapter<T>) new TypeAdapter<EventsMetric>() {
           @Override
           public void write(JsonWriter out, EventsMetric value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EventsMetric read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EventsMetric given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EventsMetric
   * @throws IOException if the JSON string is invalid with respect to EventsMetric
   */
  public static EventsMetric fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EventsMetric.class);
  }

  /**
   * Convert an instance of EventsMetric to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

