/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.ThemeColor;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * FontConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class FontConfig {
  public static final String SERIALIZED_NAME_BOLD = "bold";
  @SerializedName(SERIALIZED_NAME_BOLD)
  @javax.annotation.Nullable
  private Boolean bold;

  public static final String SERIALIZED_NAME_COLOR = "color";
  @SerializedName(SERIALIZED_NAME_COLOR)
  @javax.annotation.Nullable
  private ThemeColor color;

  /**
   *  - PAGE_THEME_FONT_FAMILY_UNSPECIFIED: Maps to the default system sans-serif stack.
   */
  @JsonAdapter(FamilyEnum.Adapter.class)
  public enum FamilyEnum {
    PAGE_THEME_FONT_FAMILY_UNSPECIFIED("PAGE_THEME_FONT_FAMILY_UNSPECIFIED"),
    
    PAGE_THEME_FONT_FAMILY_DEFAULT("PAGE_THEME_FONT_FAMILY_DEFAULT"),
    
    PAGE_THEME_FONT_FAMILY_ARIAL("PAGE_THEME_FONT_FAMILY_ARIAL"),
    
    PAGE_THEME_FONT_FAMILY_HELVETICA("PAGE_THEME_FONT_FAMILY_HELVETICA"),
    
    PAGE_THEME_FONT_FAMILY_VERDANA("PAGE_THEME_FONT_FAMILY_VERDANA"),
    
    PAGE_THEME_FONT_FAMILY_GEORGIA("PAGE_THEME_FONT_FAMILY_GEORGIA"),
    
    PAGE_THEME_FONT_FAMILY_TIMES_NEW_ROMAN("PAGE_THEME_FONT_FAMILY_TIMES_NEW_ROMAN"),
    
    PAGE_THEME_FONT_FAMILY_COURIER_NEW("PAGE_THEME_FONT_FAMILY_COURIER_NEW");

    private String value;

    FamilyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FamilyEnum fromValue(String value) {
      for (FamilyEnum b : FamilyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FamilyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FamilyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FamilyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FamilyEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      FamilyEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_FAMILY = "family";
  @SerializedName(SERIALIZED_NAME_FAMILY)
  @javax.annotation.Nullable
  private FamilyEnum family;

  public static final String SERIALIZED_NAME_FONT_SIZE = "fontSize";
  @SerializedName(SERIALIZED_NAME_FONT_SIZE)
  @javax.annotation.Nullable
  private Integer fontSize;

  public static final String SERIALIZED_NAME_ITALIC = "italic";
  @SerializedName(SERIALIZED_NAME_ITALIC)
  @javax.annotation.Nullable
  private Boolean italic;

  public FontConfig() {
  }

  public FontConfig bold(@javax.annotation.Nullable Boolean bold) {
    this.bold = bold;
    return this;
  }

  /**
   * Get bold
   * @return bold
   */
  @javax.annotation.Nullable
  public Boolean getBold() {
    return bold;
  }

  public void setBold(@javax.annotation.Nullable Boolean bold) {
    this.bold = bold;
  }


  public FontConfig color(@javax.annotation.Nullable ThemeColor color) {
    this.color = color;
    return this;
  }

  /**
   * Get color
   * @return color
   */
  @javax.annotation.Nullable
  public ThemeColor getColor() {
    return color;
  }

  public void setColor(@javax.annotation.Nullable ThemeColor color) {
    this.color = color;
  }


  public FontConfig family(@javax.annotation.Nullable FamilyEnum family) {
    this.family = family;
    return this;
  }

  /**
   *  - PAGE_THEME_FONT_FAMILY_UNSPECIFIED: Maps to the default system sans-serif stack.
   * @return family
   */
  @javax.annotation.Nullable
  public FamilyEnum getFamily() {
    return family;
  }

  public void setFamily(@javax.annotation.Nullable FamilyEnum family) {
    this.family = family;
  }


  public FontConfig fontSize(@javax.annotation.Nullable Integer fontSize) {
    this.fontSize = fontSize;
    return this;
  }

  /**
   * Get fontSize
   * @return fontSize
   */
  @javax.annotation.Nullable
  public Integer getFontSize() {
    return fontSize;
  }

  public void setFontSize(@javax.annotation.Nullable Integer fontSize) {
    this.fontSize = fontSize;
  }


  public FontConfig italic(@javax.annotation.Nullable Boolean italic) {
    this.italic = italic;
    return this;
  }

  /**
   * Get italic
   * @return italic
   */
  @javax.annotation.Nullable
  public Boolean getItalic() {
    return italic;
  }

  public void setItalic(@javax.annotation.Nullable Boolean italic) {
    this.italic = italic;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FontConfig fontConfig = (FontConfig) o;
    return Objects.equals(this.bold, fontConfig.bold) &&
        Objects.equals(this.color, fontConfig.color) &&
        Objects.equals(this.family, fontConfig.family) &&
        Objects.equals(this.fontSize, fontConfig.fontSize) &&
        Objects.equals(this.italic, fontConfig.italic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bold, color, family, fontSize, italic);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FontConfig {\n");
    sb.append("    bold: ").append(toIndentedString(bold)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    fontSize: ").append(toIndentedString(fontSize)).append("\n");
    sb.append("    italic: ").append(toIndentedString(italic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("bold", "color", "family", "fontSize", "italic"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FontConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FontConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in FontConfig is not found in the empty JSON string", FontConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FontConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FontConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `color`
      if (jsonObj.get("color") != null && !jsonObj.get("color").isJsonNull()) {
        ThemeColor.validateJsonElement(jsonObj.get("color"));
      }
      if ((jsonObj.get("family") != null && !jsonObj.get("family").isJsonNull()) && !jsonObj.get("family").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `family` to be a primitive type in the JSON string but got `%s`", jsonObj.get("family").toString()));
      }
      // validate the optional field `family`
      if (jsonObj.get("family") != null && !jsonObj.get("family").isJsonNull()) {
        FamilyEnum.validateJsonElement(jsonObj.get("family"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FontConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FontConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FontConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FontConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<FontConfig>() {
           @Override
           public void write(JsonWriter out, FontConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FontConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FontConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FontConfig
   * @throws IOException if the JSON string is invalid with respect to FontConfig
   */
  public static FontConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FontConfig.class);
  }

  /**
   * Convert an instance of FontConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

