/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.FormTraceDataField;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * FormTraceData stores summary data about a form interaction.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class FormTraceData {
  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  @javax.annotation.Nullable
  private String action;

  public static final String SERIALIZED_NAME_AUTO_SKIP_IF_KNOWN = "autoSkipIfKnown";
  @SerializedName(SERIALIZED_NAME_AUTO_SKIP_IF_KNOWN)
  @javax.annotation.Nullable
  private Boolean autoSkipIfKnown;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  @javax.annotation.Nullable
  private List<FormTraceDataField> fields = new ArrayList<>();

  public static final String SERIALIZED_NAME_SKIP_BUTTON_TEXT = "skipButtonText";
  @SerializedName(SERIALIZED_NAME_SKIP_BUTTON_TEXT)
  @javax.annotation.Nullable
  private String skipButtonText;

  public static final String SERIALIZED_NAME_SKIP_METHOD = "skipMethod";
  @SerializedName(SERIALIZED_NAME_SKIP_METHOD)
  @javax.annotation.Nullable
  private String skipMethod;

  public static final String SERIALIZED_NAME_SKIPPED = "skipped";
  @SerializedName(SERIALIZED_NAME_SKIPPED)
  @javax.annotation.Nullable
  private Boolean skipped;

  public static final String SERIALIZED_NAME_SUBMIT_BUTTON_TEXT = "submitButtonText";
  @SerializedName(SERIALIZED_NAME_SUBMIT_BUTTON_TEXT)
  @javax.annotation.Nullable
  private String submitButtonText;

  public static final String SERIALIZED_NAME_SUBMITTED_FIELDS = "submittedFields";
  @SerializedName(SERIALIZED_NAME_SUBMITTED_FIELDS)
  @javax.annotation.Nullable
  private Integer submittedFields;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_TOTAL_FIELDS = "totalFields";
  @SerializedName(SERIALIZED_NAME_TOTAL_FIELDS)
  @javax.annotation.Nullable
  private Integer totalFields;

  public FormTraceData() {
  }

  public FormTraceData action(@javax.annotation.Nullable String action) {
    this.action = action;
    return this;
  }

  /**
   * Get action
   * @return action
   */
  @javax.annotation.Nullable
  public String getAction() {
    return action;
  }

  public void setAction(@javax.annotation.Nullable String action) {
    this.action = action;
  }


  public FormTraceData autoSkipIfKnown(@javax.annotation.Nullable Boolean autoSkipIfKnown) {
    this.autoSkipIfKnown = autoSkipIfKnown;
    return this;
  }

  /**
   * Get autoSkipIfKnown
   * @return autoSkipIfKnown
   */
  @javax.annotation.Nullable
  public Boolean getAutoSkipIfKnown() {
    return autoSkipIfKnown;
  }

  public void setAutoSkipIfKnown(@javax.annotation.Nullable Boolean autoSkipIfKnown) {
    this.autoSkipIfKnown = autoSkipIfKnown;
  }


  public FormTraceData description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public FormTraceData fields(@javax.annotation.Nullable List<FormTraceDataField> fields) {
    this.fields = fields;
    return this;
  }

  public FormTraceData addFieldsItem(FormTraceDataField fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

  /**
   * Get fields
   * @return fields
   */
  @javax.annotation.Nullable
  public List<FormTraceDataField> getFields() {
    return fields;
  }

  public void setFields(@javax.annotation.Nullable List<FormTraceDataField> fields) {
    this.fields = fields;
  }


  public FormTraceData skipButtonText(@javax.annotation.Nullable String skipButtonText) {
    this.skipButtonText = skipButtonText;
    return this;
  }

  /**
   * Get skipButtonText
   * @return skipButtonText
   */
  @javax.annotation.Nullable
  public String getSkipButtonText() {
    return skipButtonText;
  }

  public void setSkipButtonText(@javax.annotation.Nullable String skipButtonText) {
    this.skipButtonText = skipButtonText;
  }


  public FormTraceData skipMethod(@javax.annotation.Nullable String skipMethod) {
    this.skipMethod = skipMethod;
    return this;
  }

  /**
   * Get skipMethod
   * @return skipMethod
   */
  @javax.annotation.Nullable
  public String getSkipMethod() {
    return skipMethod;
  }

  public void setSkipMethod(@javax.annotation.Nullable String skipMethod) {
    this.skipMethod = skipMethod;
  }


  public FormTraceData skipped(@javax.annotation.Nullable Boolean skipped) {
    this.skipped = skipped;
    return this;
  }

  /**
   * Get skipped
   * @return skipped
   */
  @javax.annotation.Nullable
  public Boolean getSkipped() {
    return skipped;
  }

  public void setSkipped(@javax.annotation.Nullable Boolean skipped) {
    this.skipped = skipped;
  }


  public FormTraceData submitButtonText(@javax.annotation.Nullable String submitButtonText) {
    this.submitButtonText = submitButtonText;
    return this;
  }

  /**
   * Get submitButtonText
   * @return submitButtonText
   */
  @javax.annotation.Nullable
  public String getSubmitButtonText() {
    return submitButtonText;
  }

  public void setSubmitButtonText(@javax.annotation.Nullable String submitButtonText) {
    this.submitButtonText = submitButtonText;
  }


  public FormTraceData submittedFields(@javax.annotation.Nullable Integer submittedFields) {
    this.submittedFields = submittedFields;
    return this;
  }

  /**
   * Get submittedFields
   * @return submittedFields
   */
  @javax.annotation.Nullable
  public Integer getSubmittedFields() {
    return submittedFields;
  }

  public void setSubmittedFields(@javax.annotation.Nullable Integer submittedFields) {
    this.submittedFields = submittedFields;
  }


  public FormTraceData title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public FormTraceData totalFields(@javax.annotation.Nullable Integer totalFields) {
    this.totalFields = totalFields;
    return this;
  }

  /**
   * Get totalFields
   * @return totalFields
   */
  @javax.annotation.Nullable
  public Integer getTotalFields() {
    return totalFields;
  }

  public void setTotalFields(@javax.annotation.Nullable Integer totalFields) {
    this.totalFields = totalFields;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FormTraceData formTraceData = (FormTraceData) o;
    return Objects.equals(this.action, formTraceData.action) &&
        Objects.equals(this.autoSkipIfKnown, formTraceData.autoSkipIfKnown) &&
        Objects.equals(this.description, formTraceData.description) &&
        Objects.equals(this.fields, formTraceData.fields) &&
        Objects.equals(this.skipButtonText, formTraceData.skipButtonText) &&
        Objects.equals(this.skipMethod, formTraceData.skipMethod) &&
        Objects.equals(this.skipped, formTraceData.skipped) &&
        Objects.equals(this.submitButtonText, formTraceData.submitButtonText) &&
        Objects.equals(this.submittedFields, formTraceData.submittedFields) &&
        Objects.equals(this.title, formTraceData.title) &&
        Objects.equals(this.totalFields, formTraceData.totalFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, autoSkipIfKnown, description, fields, skipButtonText, skipMethod, skipped, submitButtonText, submittedFields, title, totalFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FormTraceData {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    autoSkipIfKnown: ").append(toIndentedString(autoSkipIfKnown)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    skipButtonText: ").append(toIndentedString(skipButtonText)).append("\n");
    sb.append("    skipMethod: ").append(toIndentedString(skipMethod)).append("\n");
    sb.append("    skipped: ").append(toIndentedString(skipped)).append("\n");
    sb.append("    submitButtonText: ").append(toIndentedString(submitButtonText)).append("\n");
    sb.append("    submittedFields: ").append(toIndentedString(submittedFields)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    totalFields: ").append(toIndentedString(totalFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("action", "autoSkipIfKnown", "description", "fields", "skipButtonText", "skipMethod", "skipped", "submitButtonText", "submittedFields", "title", "totalFields"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FormTraceData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FormTraceData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in FormTraceData is not found in the empty JSON string", FormTraceData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FormTraceData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FormTraceData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("action") != null && !jsonObj.get("action").isJsonNull()) && !jsonObj.get("action").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `action` to be a primitive type in the JSON string but got `%s`", jsonObj.get("action").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (jsonObj.get("fields") != null && !jsonObj.get("fields").isJsonNull()) {
        JsonArray jsonArrayfields = jsonObj.getAsJsonArray("fields");
        if (jsonArrayfields != null) {
          // ensure the json data is an array
          if (!jsonObj.get("fields").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fields` to be an array in the JSON string but got `%s`", jsonObj.get("fields").toString()));
          }

          // validate the optional field `fields` (array)
          for (int i = 0; i < jsonArrayfields.size(); i++) {
            FormTraceDataField.validateJsonElement(jsonArrayfields.get(i));
          };
        }
      }
      if ((jsonObj.get("skipButtonText") != null && !jsonObj.get("skipButtonText").isJsonNull()) && !jsonObj.get("skipButtonText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `skipButtonText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("skipButtonText").toString()));
      }
      if ((jsonObj.get("skipMethod") != null && !jsonObj.get("skipMethod").isJsonNull()) && !jsonObj.get("skipMethod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `skipMethod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("skipMethod").toString()));
      }
      if ((jsonObj.get("submitButtonText") != null && !jsonObj.get("submitButtonText").isJsonNull()) && !jsonObj.get("submitButtonText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `submitButtonText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("submitButtonText").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FormTraceData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FormTraceData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FormTraceData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FormTraceData.class));

       return (TypeAdapter<T>) new TypeAdapter<FormTraceData>() {
           @Override
           public void write(JsonWriter out, FormTraceData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FormTraceData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FormTraceData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FormTraceData
   * @throws IOException if the JSON string is invalid with respect to FormTraceData
   */
  public static FormTraceData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FormTraceData.class);
  }

  /**
   * Convert an instance of FormTraceData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

