/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * GetEventsTimeSeriesRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class GetEventsTimeSeriesRequest {
  public static final String SERIALIZED_NAME_END_DATE = "endDate";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime endDate;

  public static final String SERIALIZED_NAME_INTERVAL_IN_MINUTES = "intervalInMinutes";
  @SerializedName(SERIALIZED_NAME_INTERVAL_IN_MINUTES)
  @javax.annotation.Nullable
  private Integer intervalInMinutes;

  public static final String SERIALIZED_NAME_LINK_ID = "linkId";
  @SerializedName(SERIALIZED_NAME_LINK_ID)
  @javax.annotation.Nullable
  private String linkId;

  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime startDate;

  public GetEventsTimeSeriesRequest() {
  }

  public GetEventsTimeSeriesRequest endDate(@javax.annotation.Nullable OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * Get endDate
   * @return endDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(@javax.annotation.Nullable OffsetDateTime endDate) {
    this.endDate = endDate;
  }


  public GetEventsTimeSeriesRequest intervalInMinutes(@javax.annotation.Nullable Integer intervalInMinutes) {
    this.intervalInMinutes = intervalInMinutes;
    return this;
  }

  /**
   * Get intervalInMinutes
   * @return intervalInMinutes
   */
  @javax.annotation.Nullable
  public Integer getIntervalInMinutes() {
    return intervalInMinutes;
  }

  public void setIntervalInMinutes(@javax.annotation.Nullable Integer intervalInMinutes) {
    this.intervalInMinutes = intervalInMinutes;
  }


  public GetEventsTimeSeriesRequest linkId(@javax.annotation.Nullable String linkId) {
    this.linkId = linkId;
    return this;
  }

  /**
   * Optional filtering by link ID
   * @return linkId
   */
  @javax.annotation.Nullable
  public String getLinkId() {
    return linkId;
  }

  public void setLinkId(@javax.annotation.Nullable String linkId) {
    this.linkId = linkId;
  }


  public GetEventsTimeSeriesRequest startDate(@javax.annotation.Nullable OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * Get startDate
   * @return startDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(@javax.annotation.Nullable OffsetDateTime startDate) {
    this.startDate = startDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEventsTimeSeriesRequest getEventsTimeSeriesRequest = (GetEventsTimeSeriesRequest) o;
    return Objects.equals(this.endDate, getEventsTimeSeriesRequest.endDate) &&
        Objects.equals(this.intervalInMinutes, getEventsTimeSeriesRequest.intervalInMinutes) &&
        Objects.equals(this.linkId, getEventsTimeSeriesRequest.linkId) &&
        Objects.equals(this.startDate, getEventsTimeSeriesRequest.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endDate, intervalInMinutes, linkId, startDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEventsTimeSeriesRequest {\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    intervalInMinutes: ").append(toIndentedString(intervalInMinutes)).append("\n");
    sb.append("    linkId: ").append(toIndentedString(linkId)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("endDate", "intervalInMinutes", "linkId", "startDate"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetEventsTimeSeriesRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetEventsTimeSeriesRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetEventsTimeSeriesRequest is not found in the empty JSON string", GetEventsTimeSeriesRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetEventsTimeSeriesRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetEventsTimeSeriesRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("linkId") != null && !jsonObj.get("linkId").isJsonNull()) && !jsonObj.get("linkId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `linkId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("linkId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetEventsTimeSeriesRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetEventsTimeSeriesRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetEventsTimeSeriesRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetEventsTimeSeriesRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<GetEventsTimeSeriesRequest>() {
           @Override
           public void write(JsonWriter out, GetEventsTimeSeriesRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetEventsTimeSeriesRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetEventsTimeSeriesRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetEventsTimeSeriesRequest
   * @throws IOException if the JSON string is invalid with respect to GetEventsTimeSeriesRequest
   */
  public static GetEventsTimeSeriesRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetEventsTimeSeriesRequest.class);
  }

  /**
   * Convert an instance of GetEventsTimeSeriesRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

