/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.ListEventsCsvResponse;
import com.linkbreakers.model.ListEventsJsonResponse;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * ListEventsResponse contains either the JSON payload or CSV export for the matching events.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ListEventsResponse {
  public static final String SERIALIZED_NAME_CSV = "csv";
  @SerializedName(SERIALIZED_NAME_CSV)
  @javax.annotation.Nullable
  private ListEventsCsvResponse csv;

  public static final String SERIALIZED_NAME_JSON = "json";
  @SerializedName(SERIALIZED_NAME_JSON)
  @javax.annotation.Nullable
  private ListEventsJsonResponse json;

  public ListEventsResponse() {
  }

  public ListEventsResponse csv(@javax.annotation.Nullable ListEventsCsvResponse csv) {
    this.csv = csv;
    return this;
  }

  /**
   * Get csv
   * @return csv
   */
  @javax.annotation.Nullable
  public ListEventsCsvResponse getCsv() {
    return csv;
  }

  public void setCsv(@javax.annotation.Nullable ListEventsCsvResponse csv) {
    this.csv = csv;
  }


  public ListEventsResponse json(@javax.annotation.Nullable ListEventsJsonResponse json) {
    this.json = json;
    return this;
  }

  /**
   * Get json
   * @return json
   */
  @javax.annotation.Nullable
  public ListEventsJsonResponse getJson() {
    return json;
  }

  public void setJson(@javax.annotation.Nullable ListEventsJsonResponse json) {
    this.json = json;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListEventsResponse listEventsResponse = (ListEventsResponse) o;
    return Objects.equals(this.csv, listEventsResponse.csv) &&
        Objects.equals(this.json, listEventsResponse.json);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csv, json);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListEventsResponse {\n");
    sb.append("    csv: ").append(toIndentedString(csv)).append("\n");
    sb.append("    json: ").append(toIndentedString(json)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("csv", "json"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListEventsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListEventsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ListEventsResponse is not found in the empty JSON string", ListEventsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListEventsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ListEventsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `csv`
      if (jsonObj.get("csv") != null && !jsonObj.get("csv").isJsonNull()) {
        ListEventsCsvResponse.validateJsonElement(jsonObj.get("csv"));
      }
      // validate the optional field `json`
      if (jsonObj.get("json") != null && !jsonObj.get("json").isJsonNull()) {
        ListEventsJsonResponse.validateJsonElement(jsonObj.get("json"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListEventsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListEventsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListEventsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListEventsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ListEventsResponse>() {
           @Override
           public void write(JsonWriter out, ListEventsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListEventsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListEventsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListEventsResponse
   * @throws IOException if the JSON string is invalid with respect to ListEventsResponse
   */
  public static ListEventsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListEventsResponse.class);
  }

  /**
   * Convert an instance of ListEventsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

