/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * - OUTPUT_FILE_FORMAT_UNSPECIFIED: Output format not specified (defaults to PNG server-side)  - OUTPUT_FILE_FORMAT_SVG: Scalable Vector Graphics format for infinite resolution  - OUTPUT_FILE_FORMAT_PNG: Portable Network Graphics format with transparency support  - OUTPUT_FILE_FORMAT_JPEG: Joint Photographic Experts Group format for compressed images  - OUTPUT_FILE_FORMAT_WEBP: WebP format for modern web-optimized compression
 */
@JsonAdapter(OutputFileFormat.Adapter.class)
public enum OutputFileFormat {
  
  OUTPUT_FILE_FORMAT_UNSPECIFIED("OUTPUT_FILE_FORMAT_UNSPECIFIED"),
  
  OUTPUT_FILE_FORMAT_SVG("OUTPUT_FILE_FORMAT_SVG"),
  
  OUTPUT_FILE_FORMAT_PNG("OUTPUT_FILE_FORMAT_PNG"),
  
  OUTPUT_FILE_FORMAT_JPEG("OUTPUT_FILE_FORMAT_JPEG"),
  
  OUTPUT_FILE_FORMAT_WEBP("OUTPUT_FILE_FORMAT_WEBP");

  private String value;

  OutputFileFormat(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OutputFileFormat fromValue(String value) {
    for (OutputFileFormat b : OutputFileFormat.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OutputFileFormat> {
    @Override
    public void write(final JsonWriter jsonWriter, final OutputFileFormat enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OutputFileFormat read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OutputFileFormat.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    OutputFileFormat.fromValue(value);
  }
}

