/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PageThemeContainerVariant
 */
@JsonAdapter(PageThemeContainerVariant.Adapter.class)
public enum PageThemeContainerVariant {
  
  PAGE_THEME_CONTAINER_VARIANT_UNSPECIFIED("PAGE_THEME_CONTAINER_VARIANT_UNSPECIFIED"),
  
  PAGE_THEME_CONTAINER_VARIANT_ROUNDED("PAGE_THEME_CONTAINER_VARIANT_ROUNDED"),
  
  PAGE_THEME_CONTAINER_VARIANT_SQUARE("PAGE_THEME_CONTAINER_VARIANT_SQUARE");

  private String value;

  PageThemeContainerVariant(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PageThemeContainerVariant fromValue(String value) {
    for (PageThemeContainerVariant b : PageThemeContainerVariant.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PageThemeContainerVariant> {
    @Override
    public void write(final JsonWriter jsonWriter, final PageThemeContainerVariant enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PageThemeContainerVariant read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PageThemeContainerVariant.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PageThemeContainerVariant.fromValue(value);
  }
}

