/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.ContainerConfig;
import com.linkbreakers.model.FontConfig;
import com.linkbreakers.model.ThemeColor;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * PageTheme
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class PageTheme {
  public static final String SERIALIZED_NAME_BADGE_ENABLED = "badgeEnabled";
  @SerializedName(SERIALIZED_NAME_BADGE_ENABLED)
  @javax.annotation.Nullable
  private Boolean badgeEnabled;

  public static final String SERIALIZED_NAME_BADGE_ICON_COLOR = "badgeIconColor";
  @SerializedName(SERIALIZED_NAME_BADGE_ICON_COLOR)
  @javax.annotation.Nullable
  private ThemeColor badgeIconColor;

  public static final String SERIALIZED_NAME_BADGE_ID = "badgeId";
  @SerializedName(SERIALIZED_NAME_BADGE_ID)
  @javax.annotation.Nullable
  private String badgeId;

  /**
   * Gets or Sets badgeShape
   */
  @JsonAdapter(BadgeShapeEnum.Adapter.class)
  public enum BadgeShapeEnum {
    PAGE_THEME_BADGE_SHAPE_UNSPECIFIED("PAGE_THEME_BADGE_SHAPE_UNSPECIFIED"),
    
    PAGE_THEME_BADGE_SHAPE_CIRCLE("PAGE_THEME_BADGE_SHAPE_CIRCLE"),
    
    PAGE_THEME_BADGE_SHAPE_SQUARE("PAGE_THEME_BADGE_SHAPE_SQUARE"),
    
    PAGE_THEME_BADGE_SHAPE_ROUNDED("PAGE_THEME_BADGE_SHAPE_ROUNDED");

    private String value;

    BadgeShapeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BadgeShapeEnum fromValue(String value) {
      for (BadgeShapeEnum b : BadgeShapeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BadgeShapeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BadgeShapeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BadgeShapeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BadgeShapeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      BadgeShapeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_BADGE_SHAPE = "badgeShape";
  @SerializedName(SERIALIZED_NAME_BADGE_SHAPE)
  @javax.annotation.Nullable
  private BadgeShapeEnum badgeShape;

  public static final String SERIALIZED_NAME_BODY_FONT = "bodyFont";
  @SerializedName(SERIALIZED_NAME_BODY_FONT)
  @javax.annotation.Nullable
  private FontConfig bodyFont;

  public static final String SERIALIZED_NAME_CANVAS_COLOR = "canvasColor";
  @SerializedName(SERIALIZED_NAME_CANVAS_COLOR)
  @javax.annotation.Nullable
  private ThemeColor canvasColor;

  public static final String SERIALIZED_NAME_CANVAS_COVER_ID = "canvasCoverId";
  @SerializedName(SERIALIZED_NAME_CANVAS_COVER_ID)
  @javax.annotation.Nullable
  private String canvasCoverId;

  /**
   * Gets or Sets canvasCoverMode
   */
  @JsonAdapter(CanvasCoverModeEnum.Adapter.class)
  public enum CanvasCoverModeEnum {
    PAGE_THEME_BACKGROUND_COVER_MODE_UNSPECIFIED("PAGE_THEME_BACKGROUND_COVER_MODE_UNSPECIFIED"),
    
    PAGE_THEME_BACKGROUND_COVER_MODE_FULL("PAGE_THEME_BACKGROUND_COVER_MODE_FULL"),
    
    PAGE_THEME_BACKGROUND_COVER_MODE_PROGRESSIVE_TOP("PAGE_THEME_BACKGROUND_COVER_MODE_PROGRESSIVE_TOP"),
    
    PAGE_THEME_BACKGROUND_COVER_MODE_PROGRESSIVE_BOTTOM("PAGE_THEME_BACKGROUND_COVER_MODE_PROGRESSIVE_BOTTOM");

    private String value;

    CanvasCoverModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CanvasCoverModeEnum fromValue(String value) {
      for (CanvasCoverModeEnum b : CanvasCoverModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CanvasCoverModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CanvasCoverModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CanvasCoverModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CanvasCoverModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CanvasCoverModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CANVAS_COVER_MODE = "canvasCoverMode";
  @SerializedName(SERIALIZED_NAME_CANVAS_COVER_MODE)
  @javax.annotation.Nullable
  private CanvasCoverModeEnum canvasCoverMode;

  public static final String SERIALIZED_NAME_CONTAINER_CONFIG = "containerConfig";
  @SerializedName(SERIALIZED_NAME_CONTAINER_CONFIG)
  @javax.annotation.Nullable
  private ContainerConfig containerConfig;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_ELEMENT_COLOR = "elementColor";
  @SerializedName(SERIALIZED_NAME_ELEMENT_COLOR)
  @javax.annotation.Nullable
  private ThemeColor elementColor;

  public static final String SERIALIZED_NAME_ELEMENT_FONT = "elementFont";
  @SerializedName(SERIALIZED_NAME_ELEMENT_FONT)
  @javax.annotation.Nullable
  private FontConfig elementFont;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_TITLE_FONT = "titleFont";
  @SerializedName(SERIALIZED_NAME_TITLE_FONT)
  @javax.annotation.Nullable
  private FontConfig titleFont;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_WORKSPACE_ID = "workspaceId";
  @SerializedName(SERIALIZED_NAME_WORKSPACE_ID)
  @javax.annotation.Nullable
  private String workspaceId;

  public PageTheme() {
  }

  public PageTheme(
     OffsetDateTime createdAt, 
     String id, 
     OffsetDateTime updatedAt, 
     String workspaceId
  ) {
    this();
    this.createdAt = createdAt;
    this.id = id;
    this.updatedAt = updatedAt;
    this.workspaceId = workspaceId;
  }

  public PageTheme badgeEnabled(@javax.annotation.Nullable Boolean badgeEnabled) {
    this.badgeEnabled = badgeEnabled;
    return this;
  }

  /**
   * Get badgeEnabled
   * @return badgeEnabled
   */
  @javax.annotation.Nullable
  public Boolean getBadgeEnabled() {
    return badgeEnabled;
  }

  public void setBadgeEnabled(@javax.annotation.Nullable Boolean badgeEnabled) {
    this.badgeEnabled = badgeEnabled;
  }


  public PageTheme badgeIconColor(@javax.annotation.Nullable ThemeColor badgeIconColor) {
    this.badgeIconColor = badgeIconColor;
    return this;
  }

  /**
   * Get badgeIconColor
   * @return badgeIconColor
   */
  @javax.annotation.Nullable
  public ThemeColor getBadgeIconColor() {
    return badgeIconColor;
  }

  public void setBadgeIconColor(@javax.annotation.Nullable ThemeColor badgeIconColor) {
    this.badgeIconColor = badgeIconColor;
  }


  public PageTheme badgeId(@javax.annotation.Nullable String badgeId) {
    this.badgeId = badgeId;
    return this;
  }

  /**
   * Get badgeId
   * @return badgeId
   */
  @javax.annotation.Nullable
  public String getBadgeId() {
    return badgeId;
  }

  public void setBadgeId(@javax.annotation.Nullable String badgeId) {
    this.badgeId = badgeId;
  }


  public PageTheme badgeShape(@javax.annotation.Nullable BadgeShapeEnum badgeShape) {
    this.badgeShape = badgeShape;
    return this;
  }

  /**
   * Get badgeShape
   * @return badgeShape
   */
  @javax.annotation.Nullable
  public BadgeShapeEnum getBadgeShape() {
    return badgeShape;
  }

  public void setBadgeShape(@javax.annotation.Nullable BadgeShapeEnum badgeShape) {
    this.badgeShape = badgeShape;
  }


  public PageTheme bodyFont(@javax.annotation.Nullable FontConfig bodyFont) {
    this.bodyFont = bodyFont;
    return this;
  }

  /**
   * Get bodyFont
   * @return bodyFont
   */
  @javax.annotation.Nullable
  public FontConfig getBodyFont() {
    return bodyFont;
  }

  public void setBodyFont(@javax.annotation.Nullable FontConfig bodyFont) {
    this.bodyFont = bodyFont;
  }


  public PageTheme canvasColor(@javax.annotation.Nullable ThemeColor canvasColor) {
    this.canvasColor = canvasColor;
    return this;
  }

  /**
   * Get canvasColor
   * @return canvasColor
   */
  @javax.annotation.Nullable
  public ThemeColor getCanvasColor() {
    return canvasColor;
  }

  public void setCanvasColor(@javax.annotation.Nullable ThemeColor canvasColor) {
    this.canvasColor = canvasColor;
  }


  public PageTheme canvasCoverId(@javax.annotation.Nullable String canvasCoverId) {
    this.canvasCoverId = canvasCoverId;
    return this;
  }

  /**
   * Get canvasCoverId
   * @return canvasCoverId
   */
  @javax.annotation.Nullable
  public String getCanvasCoverId() {
    return canvasCoverId;
  }

  public void setCanvasCoverId(@javax.annotation.Nullable String canvasCoverId) {
    this.canvasCoverId = canvasCoverId;
  }


  public PageTheme canvasCoverMode(@javax.annotation.Nullable CanvasCoverModeEnum canvasCoverMode) {
    this.canvasCoverMode = canvasCoverMode;
    return this;
  }

  /**
   * Get canvasCoverMode
   * @return canvasCoverMode
   */
  @javax.annotation.Nullable
  public CanvasCoverModeEnum getCanvasCoverMode() {
    return canvasCoverMode;
  }

  public void setCanvasCoverMode(@javax.annotation.Nullable CanvasCoverModeEnum canvasCoverMode) {
    this.canvasCoverMode = canvasCoverMode;
  }


  public PageTheme containerConfig(@javax.annotation.Nullable ContainerConfig containerConfig) {
    this.containerConfig = containerConfig;
    return this;
  }

  /**
   * Get containerConfig
   * @return containerConfig
   */
  @javax.annotation.Nullable
  public ContainerConfig getContainerConfig() {
    return containerConfig;
  }

  public void setContainerConfig(@javax.annotation.Nullable ContainerConfig containerConfig) {
    this.containerConfig = containerConfig;
  }


  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  public PageTheme elementColor(@javax.annotation.Nullable ThemeColor elementColor) {
    this.elementColor = elementColor;
    return this;
  }

  /**
   * Get elementColor
   * @return elementColor
   */
  @javax.annotation.Nullable
  public ThemeColor getElementColor() {
    return elementColor;
  }

  public void setElementColor(@javax.annotation.Nullable ThemeColor elementColor) {
    this.elementColor = elementColor;
  }


  public PageTheme elementFont(@javax.annotation.Nullable FontConfig elementFont) {
    this.elementFont = elementFont;
    return this;
  }

  /**
   * Get elementFont
   * @return elementFont
   */
  @javax.annotation.Nullable
  public FontConfig getElementFont() {
    return elementFont;
  }

  public void setElementFont(@javax.annotation.Nullable FontConfig elementFont) {
    this.elementFont = elementFont;
  }


  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }



  public PageTheme titleFont(@javax.annotation.Nullable FontConfig titleFont) {
    this.titleFont = titleFont;
    return this;
  }

  /**
   * Get titleFont
   * @return titleFont
   */
  @javax.annotation.Nullable
  public FontConfig getTitleFont() {
    return titleFont;
  }

  public void setTitleFont(@javax.annotation.Nullable FontConfig titleFont) {
    this.titleFont = titleFont;
  }


  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }



  /**
   * Get workspaceId
   * @return workspaceId
   */
  @javax.annotation.Nullable
  public String getWorkspaceId() {
    return workspaceId;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageTheme pageTheme = (PageTheme) o;
    return Objects.equals(this.badgeEnabled, pageTheme.badgeEnabled) &&
        Objects.equals(this.badgeIconColor, pageTheme.badgeIconColor) &&
        Objects.equals(this.badgeId, pageTheme.badgeId) &&
        Objects.equals(this.badgeShape, pageTheme.badgeShape) &&
        Objects.equals(this.bodyFont, pageTheme.bodyFont) &&
        Objects.equals(this.canvasColor, pageTheme.canvasColor) &&
        Objects.equals(this.canvasCoverId, pageTheme.canvasCoverId) &&
        Objects.equals(this.canvasCoverMode, pageTheme.canvasCoverMode) &&
        Objects.equals(this.containerConfig, pageTheme.containerConfig) &&
        Objects.equals(this.createdAt, pageTheme.createdAt) &&
        Objects.equals(this.elementColor, pageTheme.elementColor) &&
        Objects.equals(this.elementFont, pageTheme.elementFont) &&
        Objects.equals(this.id, pageTheme.id) &&
        Objects.equals(this.titleFont, pageTheme.titleFont) &&
        Objects.equals(this.updatedAt, pageTheme.updatedAt) &&
        Objects.equals(this.workspaceId, pageTheme.workspaceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(badgeEnabled, badgeIconColor, badgeId, badgeShape, bodyFont, canvasColor, canvasCoverId, canvasCoverMode, containerConfig, createdAt, elementColor, elementFont, id, titleFont, updatedAt, workspaceId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageTheme {\n");
    sb.append("    badgeEnabled: ").append(toIndentedString(badgeEnabled)).append("\n");
    sb.append("    badgeIconColor: ").append(toIndentedString(badgeIconColor)).append("\n");
    sb.append("    badgeId: ").append(toIndentedString(badgeId)).append("\n");
    sb.append("    badgeShape: ").append(toIndentedString(badgeShape)).append("\n");
    sb.append("    bodyFont: ").append(toIndentedString(bodyFont)).append("\n");
    sb.append("    canvasColor: ").append(toIndentedString(canvasColor)).append("\n");
    sb.append("    canvasCoverId: ").append(toIndentedString(canvasCoverId)).append("\n");
    sb.append("    canvasCoverMode: ").append(toIndentedString(canvasCoverMode)).append("\n");
    sb.append("    containerConfig: ").append(toIndentedString(containerConfig)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    elementColor: ").append(toIndentedString(elementColor)).append("\n");
    sb.append("    elementFont: ").append(toIndentedString(elementFont)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    titleFont: ").append(toIndentedString(titleFont)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    workspaceId: ").append(toIndentedString(workspaceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("badgeEnabled", "badgeIconColor", "badgeId", "badgeShape", "bodyFont", "canvasColor", "canvasCoverId", "canvasCoverMode", "containerConfig", "createdAt", "elementColor", "elementFont", "id", "titleFont", "updatedAt", "workspaceId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PageTheme
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PageTheme.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PageTheme is not found in the empty JSON string", PageTheme.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PageTheme.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PageTheme` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `badgeIconColor`
      if (jsonObj.get("badgeIconColor") != null && !jsonObj.get("badgeIconColor").isJsonNull()) {
        ThemeColor.validateJsonElement(jsonObj.get("badgeIconColor"));
      }
      if ((jsonObj.get("badgeId") != null && !jsonObj.get("badgeId").isJsonNull()) && !jsonObj.get("badgeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `badgeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("badgeId").toString()));
      }
      if ((jsonObj.get("badgeShape") != null && !jsonObj.get("badgeShape").isJsonNull()) && !jsonObj.get("badgeShape").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `badgeShape` to be a primitive type in the JSON string but got `%s`", jsonObj.get("badgeShape").toString()));
      }
      // validate the optional field `badgeShape`
      if (jsonObj.get("badgeShape") != null && !jsonObj.get("badgeShape").isJsonNull()) {
        BadgeShapeEnum.validateJsonElement(jsonObj.get("badgeShape"));
      }
      // validate the optional field `bodyFont`
      if (jsonObj.get("bodyFont") != null && !jsonObj.get("bodyFont").isJsonNull()) {
        FontConfig.validateJsonElement(jsonObj.get("bodyFont"));
      }
      // validate the optional field `canvasColor`
      if (jsonObj.get("canvasColor") != null && !jsonObj.get("canvasColor").isJsonNull()) {
        ThemeColor.validateJsonElement(jsonObj.get("canvasColor"));
      }
      if ((jsonObj.get("canvasCoverId") != null && !jsonObj.get("canvasCoverId").isJsonNull()) && !jsonObj.get("canvasCoverId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `canvasCoverId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("canvasCoverId").toString()));
      }
      if ((jsonObj.get("canvasCoverMode") != null && !jsonObj.get("canvasCoverMode").isJsonNull()) && !jsonObj.get("canvasCoverMode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `canvasCoverMode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("canvasCoverMode").toString()));
      }
      // validate the optional field `canvasCoverMode`
      if (jsonObj.get("canvasCoverMode") != null && !jsonObj.get("canvasCoverMode").isJsonNull()) {
        CanvasCoverModeEnum.validateJsonElement(jsonObj.get("canvasCoverMode"));
      }
      // validate the optional field `containerConfig`
      if (jsonObj.get("containerConfig") != null && !jsonObj.get("containerConfig").isJsonNull()) {
        ContainerConfig.validateJsonElement(jsonObj.get("containerConfig"));
      }
      // validate the optional field `elementColor`
      if (jsonObj.get("elementColor") != null && !jsonObj.get("elementColor").isJsonNull()) {
        ThemeColor.validateJsonElement(jsonObj.get("elementColor"));
      }
      // validate the optional field `elementFont`
      if (jsonObj.get("elementFont") != null && !jsonObj.get("elementFont").isJsonNull()) {
        FontConfig.validateJsonElement(jsonObj.get("elementFont"));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the optional field `titleFont`
      if (jsonObj.get("titleFont") != null && !jsonObj.get("titleFont").isJsonNull()) {
        FontConfig.validateJsonElement(jsonObj.get("titleFont"));
      }
      if ((jsonObj.get("workspaceId") != null && !jsonObj.get("workspaceId").isJsonNull()) && !jsonObj.get("workspaceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `workspaceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workspaceId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PageTheme.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PageTheme' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PageTheme> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PageTheme.class));

       return (TypeAdapter<T>) new TypeAdapter<PageTheme>() {
           @Override
           public void write(JsonWriter out, PageTheme value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PageTheme read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PageTheme given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PageTheme
   * @throws IOException if the JSON string is invalid with respect to PageTheme
   */
  public static PageTheme fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PageTheme.class);
  }

  /**
   * Convert an instance of PageTheme to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

