/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PageThemeBadgeShape
 */
@JsonAdapter(PageThemeBadgeShape.Adapter.class)
public enum PageThemeBadgeShape {
  
  PAGE_THEME_BADGE_SHAPE_UNSPECIFIED("PAGE_THEME_BADGE_SHAPE_UNSPECIFIED"),
  
  PAGE_THEME_BADGE_SHAPE_CIRCLE("PAGE_THEME_BADGE_SHAPE_CIRCLE"),
  
  PAGE_THEME_BADGE_SHAPE_SQUARE("PAGE_THEME_BADGE_SHAPE_SQUARE"),
  
  PAGE_THEME_BADGE_SHAPE_ROUNDED("PAGE_THEME_BADGE_SHAPE_ROUNDED");

  private String value;

  PageThemeBadgeShape(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PageThemeBadgeShape fromValue(String value) {
    for (PageThemeBadgeShape b : PageThemeBadgeShape.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PageThemeBadgeShape> {
    @Override
    public void write(final JsonWriter jsonWriter, final PageThemeBadgeShape enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PageThemeBadgeShape read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PageThemeBadgeShape.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PageThemeBadgeShape.fromValue(value);
  }
}

