/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.125.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.PublicPageThemeTemplate;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * PublicListPageThemeTemplatesResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class PublicListPageThemeTemplatesResponse {
  public static final String SERIALIZED_NAME_HAS_MORE = "hasMore";
  @SerializedName(SERIALIZED_NAME_HAS_MORE)
  @javax.annotation.Nullable
  private Boolean hasMore;

  public static final String SERIALIZED_NAME_NEXT_PAGE_TOKEN = "nextPageToken";
  @SerializedName(SERIALIZED_NAME_NEXT_PAGE_TOKEN)
  @javax.annotation.Nullable
  private String nextPageToken;

  public static final String SERIALIZED_NAME_PAGE_THEME_TEMPLATES = "pageThemeTemplates";
  @SerializedName(SERIALIZED_NAME_PAGE_THEME_TEMPLATES)
  @javax.annotation.Nullable
  private List<PublicPageThemeTemplate> pageThemeTemplates = new ArrayList<>();

  public PublicListPageThemeTemplatesResponse() {
  }

  public PublicListPageThemeTemplatesResponse hasMore(@javax.annotation.Nullable Boolean hasMore) {
    this.hasMore = hasMore;
    return this;
  }

  /**
   * Get hasMore
   * @return hasMore
   */
  @javax.annotation.Nullable
  public Boolean getHasMore() {
    return hasMore;
  }

  public void setHasMore(@javax.annotation.Nullable Boolean hasMore) {
    this.hasMore = hasMore;
  }


  public PublicListPageThemeTemplatesResponse nextPageToken(@javax.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  /**
   * Get nextPageToken
   * @return nextPageToken
   */
  @javax.annotation.Nullable
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(@javax.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  public PublicListPageThemeTemplatesResponse pageThemeTemplates(@javax.annotation.Nullable List<PublicPageThemeTemplate> pageThemeTemplates) {
    this.pageThemeTemplates = pageThemeTemplates;
    return this;
  }

  public PublicListPageThemeTemplatesResponse addPageThemeTemplatesItem(PublicPageThemeTemplate pageThemeTemplatesItem) {
    if (this.pageThemeTemplates == null) {
      this.pageThemeTemplates = new ArrayList<>();
    }
    this.pageThemeTemplates.add(pageThemeTemplatesItem);
    return this;
  }

  /**
   * Get pageThemeTemplates
   * @return pageThemeTemplates
   */
  @javax.annotation.Nullable
  public List<PublicPageThemeTemplate> getPageThemeTemplates() {
    return pageThemeTemplates;
  }

  public void setPageThemeTemplates(@javax.annotation.Nullable List<PublicPageThemeTemplate> pageThemeTemplates) {
    this.pageThemeTemplates = pageThemeTemplates;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicListPageThemeTemplatesResponse publicListPageThemeTemplatesResponse = (PublicListPageThemeTemplatesResponse) o;
    return Objects.equals(this.hasMore, publicListPageThemeTemplatesResponse.hasMore) &&
        Objects.equals(this.nextPageToken, publicListPageThemeTemplatesResponse.nextPageToken) &&
        Objects.equals(this.pageThemeTemplates, publicListPageThemeTemplatesResponse.pageThemeTemplates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasMore, nextPageToken, pageThemeTemplates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicListPageThemeTemplatesResponse {\n");
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("    pageThemeTemplates: ").append(toIndentedString(pageThemeTemplates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("hasMore", "nextPageToken", "pageThemeTemplates"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PublicListPageThemeTemplatesResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PublicListPageThemeTemplatesResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PublicListPageThemeTemplatesResponse is not found in the empty JSON string", PublicListPageThemeTemplatesResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PublicListPageThemeTemplatesResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PublicListPageThemeTemplatesResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nextPageToken") != null && !jsonObj.get("nextPageToken").isJsonNull()) && !jsonObj.get("nextPageToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nextPageToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextPageToken").toString()));
      }
      if (jsonObj.get("pageThemeTemplates") != null && !jsonObj.get("pageThemeTemplates").isJsonNull()) {
        JsonArray jsonArraypageThemeTemplates = jsonObj.getAsJsonArray("pageThemeTemplates");
        if (jsonArraypageThemeTemplates != null) {
          // ensure the json data is an array
          if (!jsonObj.get("pageThemeTemplates").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `pageThemeTemplates` to be an array in the JSON string but got `%s`", jsonObj.get("pageThemeTemplates").toString()));
          }

          // validate the optional field `pageThemeTemplates` (array)
          for (int i = 0; i < jsonArraypageThemeTemplates.size(); i++) {
            PublicPageThemeTemplate.validateJsonElement(jsonArraypageThemeTemplates.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PublicListPageThemeTemplatesResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PublicListPageThemeTemplatesResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PublicListPageThemeTemplatesResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PublicListPageThemeTemplatesResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PublicListPageThemeTemplatesResponse>() {
           @Override
           public void write(JsonWriter out, PublicListPageThemeTemplatesResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PublicListPageThemeTemplatesResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PublicListPageThemeTemplatesResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PublicListPageThemeTemplatesResponse
   * @throws IOException if the JSON string is invalid with respect to PublicListPageThemeTemplatesResponse
   */
  public static PublicListPageThemeTemplatesResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PublicListPageThemeTemplatesResponse.class);
  }

  /**
   * Convert an instance of PublicListPageThemeTemplatesResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

