/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.131.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.PageThemeTemplateImages;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * ResolvePageThemeTemplateImagesResponse carries the resolved images.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ResolvePageThemeTemplateImagesResponse {
  public static final String SERIALIZED_NAME_IMAGES = "images";
  @SerializedName(SERIALIZED_NAME_IMAGES)
  @javax.annotation.Nullable
  private Map<String, PageThemeTemplateImages> images = new HashMap<>();

  public ResolvePageThemeTemplateImagesResponse() {
  }

  public ResolvePageThemeTemplateImagesResponse images(@javax.annotation.Nullable Map<String, PageThemeTemplateImages> images) {
    this.images = images;
    return this;
  }

  public ResolvePageThemeTemplateImagesResponse putImagesItem(String key, PageThemeTemplateImages imagesItem) {
    if (this.images == null) {
      this.images = new HashMap<>();
    }
    this.images.put(key, imagesItem);
    return this;
  }

  /**
   * Images by template id. These expire; fetch rather than store.
   * @return images
   */
  @javax.annotation.Nullable
  public Map<String, PageThemeTemplateImages> getImages() {
    return images;
  }

  public void setImages(@javax.annotation.Nullable Map<String, PageThemeTemplateImages> images) {
    this.images = images;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResolvePageThemeTemplateImagesResponse resolvePageThemeTemplateImagesResponse = (ResolvePageThemeTemplateImagesResponse) o;
    return Objects.equals(this.images, resolvePageThemeTemplateImagesResponse.images);
  }

  @Override
  public int hashCode() {
    return Objects.hash(images);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResolvePageThemeTemplateImagesResponse {\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("images"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResolvePageThemeTemplateImagesResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResolvePageThemeTemplateImagesResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ResolvePageThemeTemplateImagesResponse is not found in the empty JSON string", ResolvePageThemeTemplateImagesResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResolvePageThemeTemplateImagesResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ResolvePageThemeTemplateImagesResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResolvePageThemeTemplateImagesResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResolvePageThemeTemplateImagesResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResolvePageThemeTemplateImagesResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResolvePageThemeTemplateImagesResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ResolvePageThemeTemplateImagesResponse>() {
           @Override
           public void write(JsonWriter out, ResolvePageThemeTemplateImagesResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResolvePageThemeTemplateImagesResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResolvePageThemeTemplateImagesResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResolvePageThemeTemplateImagesResponse
   * @throws IOException if the JSON string is invalid with respect to ResolvePageThemeTemplateImagesResponse
   */
  public static ResolvePageThemeTemplateImagesResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResolvePageThemeTemplateImagesResponse.class);
  }

  /**
   * Convert an instance of ResolvePageThemeTemplateImagesResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

