/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.89.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.linkbreakers.model.WidgetFieldMapping;
import com.linkbreakers.model.WidgetTab;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.linkbreakers.JSON;

/**
 * WidgetVisualization
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class WidgetVisualization {
  public static final String SERIALIZED_NAME_CHART_TYPE = "chartType";
  @SerializedName(SERIALIZED_NAME_CHART_TYPE)
  @javax.annotation.Nullable
  private String chartType;

  public static final String SERIALIZED_NAME_COLORS = "colors";
  @SerializedName(SERIALIZED_NAME_COLORS)
  @javax.annotation.Nullable
  private List<String> colors = new ArrayList<>();

  public static final String SERIALIZED_NAME_FIELD_MAPPINGS = "fieldMappings";
  @SerializedName(SERIALIZED_NAME_FIELD_MAPPINGS)
  @javax.annotation.Nullable
  private List<WidgetFieldMapping> fieldMappings = new ArrayList<>();

  public static final String SERIALIZED_NAME_TABS = "tabs";
  @SerializedName(SERIALIZED_NAME_TABS)
  @javax.annotation.Nullable
  private List<WidgetTab> tabs = new ArrayList<>();

  public WidgetVisualization() {
  }

  public WidgetVisualization chartType(@javax.annotation.Nullable String chartType) {
    this.chartType = chartType;
    return this;
  }

  /**
   * Get chartType
   * @return chartType
   */
  @javax.annotation.Nullable
  public String getChartType() {
    return chartType;
  }

  public void setChartType(@javax.annotation.Nullable String chartType) {
    this.chartType = chartType;
  }


  public WidgetVisualization colors(@javax.annotation.Nullable List<String> colors) {
    this.colors = colors;
    return this;
  }

  public WidgetVisualization addColorsItem(String colorsItem) {
    if (this.colors == null) {
      this.colors = new ArrayList<>();
    }
    this.colors.add(colorsItem);
    return this;
  }

  /**
   * Get colors
   * @return colors
   */
  @javax.annotation.Nullable
  public List<String> getColors() {
    return colors;
  }

  public void setColors(@javax.annotation.Nullable List<String> colors) {
    this.colors = colors;
  }


  public WidgetVisualization fieldMappings(@javax.annotation.Nullable List<WidgetFieldMapping> fieldMappings) {
    this.fieldMappings = fieldMappings;
    return this;
  }

  public WidgetVisualization addFieldMappingsItem(WidgetFieldMapping fieldMappingsItem) {
    if (this.fieldMappings == null) {
      this.fieldMappings = new ArrayList<>();
    }
    this.fieldMappings.add(fieldMappingsItem);
    return this;
  }

  /**
   * Get fieldMappings
   * @return fieldMappings
   */
  @javax.annotation.Nullable
  public List<WidgetFieldMapping> getFieldMappings() {
    return fieldMappings;
  }

  public void setFieldMappings(@javax.annotation.Nullable List<WidgetFieldMapping> fieldMappings) {
    this.fieldMappings = fieldMappings;
  }


  public WidgetVisualization tabs(@javax.annotation.Nullable List<WidgetTab> tabs) {
    this.tabs = tabs;
    return this;
  }

  public WidgetVisualization addTabsItem(WidgetTab tabsItem) {
    if (this.tabs == null) {
      this.tabs = new ArrayList<>();
    }
    this.tabs.add(tabsItem);
    return this;
  }

  /**
   * Optional tabs for grouped views. Each tab has label and params that override the base params.
   * @return tabs
   */
  @javax.annotation.Nullable
  public List<WidgetTab> getTabs() {
    return tabs;
  }

  public void setTabs(@javax.annotation.Nullable List<WidgetTab> tabs) {
    this.tabs = tabs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetVisualization widgetVisualization = (WidgetVisualization) o;
    return Objects.equals(this.chartType, widgetVisualization.chartType) &&
        Objects.equals(this.colors, widgetVisualization.colors) &&
        Objects.equals(this.fieldMappings, widgetVisualization.fieldMappings) &&
        Objects.equals(this.tabs, widgetVisualization.tabs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chartType, colors, fieldMappings, tabs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetVisualization {\n");
    sb.append("    chartType: ").append(toIndentedString(chartType)).append("\n");
    sb.append("    colors: ").append(toIndentedString(colors)).append("\n");
    sb.append("    fieldMappings: ").append(toIndentedString(fieldMappings)).append("\n");
    sb.append("    tabs: ").append(toIndentedString(tabs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("chartType", "colors", "fieldMappings", "tabs"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WidgetVisualization
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WidgetVisualization.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WidgetVisualization is not found in the empty JSON string", WidgetVisualization.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WidgetVisualization.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `WidgetVisualization` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("chartType") != null && !jsonObj.get("chartType").isJsonNull()) && !jsonObj.get("chartType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `chartType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("chartType").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("colors") != null && !jsonObj.get("colors").isJsonNull() && !jsonObj.get("colors").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `colors` to be an array in the JSON string but got `%s`", jsonObj.get("colors").toString()));
      }
      if (jsonObj.get("fieldMappings") != null && !jsonObj.get("fieldMappings").isJsonNull()) {
        JsonArray jsonArrayfieldMappings = jsonObj.getAsJsonArray("fieldMappings");
        if (jsonArrayfieldMappings != null) {
          // ensure the json data is an array
          if (!jsonObj.get("fieldMappings").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fieldMappings` to be an array in the JSON string but got `%s`", jsonObj.get("fieldMappings").toString()));
          }

          // validate the optional field `fieldMappings` (array)
          for (int i = 0; i < jsonArrayfieldMappings.size(); i++) {
            WidgetFieldMapping.validateJsonElement(jsonArrayfieldMappings.get(i));
          };
        }
      }
      if (jsonObj.get("tabs") != null && !jsonObj.get("tabs").isJsonNull()) {
        JsonArray jsonArraytabs = jsonObj.getAsJsonArray("tabs");
        if (jsonArraytabs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("tabs").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tabs` to be an array in the JSON string but got `%s`", jsonObj.get("tabs").toString()));
          }

          // validate the optional field `tabs` (array)
          for (int i = 0; i < jsonArraytabs.size(); i++) {
            WidgetTab.validateJsonElement(jsonArraytabs.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WidgetVisualization.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WidgetVisualization' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WidgetVisualization> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WidgetVisualization.class));

       return (TypeAdapter<T>) new TypeAdapter<WidgetVisualization>() {
           @Override
           public void write(JsonWriter out, WidgetVisualization value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WidgetVisualization read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WidgetVisualization given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WidgetVisualization
   * @throws IOException if the JSON string is invalid with respect to WidgetVisualization
   */
  public static WidgetVisualization fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WidgetVisualization.class);
  }

  /**
   * Convert an instance of WidgetVisualization to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

