/*
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linkbreakers.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * - WORKSPACE_TOKEN_KEY_TYPE_UNSPECIFIED: Default value (should not be used)  - WORKSPACE_TOKEN_KEY_TYPE_SECRET: Secret key with full API access  - WORKSPACE_TOKEN_KEY_TYPE_PUBLISHABLE: Publishable key with limited access
 */
@JsonAdapter(WorkspaceTokenKeyType.Adapter.class)
public enum WorkspaceTokenKeyType {
  
  WORKSPACE_TOKEN_KEY_TYPE_UNSPECIFIED("WORKSPACE_TOKEN_KEY_TYPE_UNSPECIFIED"),
  
  WORKSPACE_TOKEN_KEY_TYPE_SECRET("WORKSPACE_TOKEN_KEY_TYPE_SECRET"),
  
  WORKSPACE_TOKEN_KEY_TYPE_PUBLISHABLE("WORKSPACE_TOKEN_KEY_TYPE_PUBLISHABLE");

  private String value;

  WorkspaceTokenKeyType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WorkspaceTokenKeyType fromValue(String value) {
    for (WorkspaceTokenKeyType b : WorkspaceTokenKeyType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<WorkspaceTokenKeyType> {
    @Override
    public void write(final JsonWriter jsonWriter, final WorkspaceTokenKeyType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WorkspaceTokenKeyType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WorkspaceTokenKeyType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    WorkspaceTokenKeyType.fromValue(value);
  }
}

